interface LearningData {
  everydayExpressions: LearningCategory[];
  greeting: LearningCategory[];
  travel: LearningCategory[];
  numberAndMoney: LearningCategory[];
  location: LearningCategory[];
  timeAndDate: LearningCategory[];
}

interface LearningCategory {
  seq: number;
  isLearning: boolean;
  isFavorite: boolean;
  word: string;
  mean: string;
  mean2: string;
  audio: string;
}

export const learningData = [
  {
    everydayExpressions: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Piece of cake",
        mean: "케이크 조각",
        mean2: "케이크 조각",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Break a leg",
        mean: "다리 부러짐",
        mean2: "다리 부러짐",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Hang in there",
        mean: "버텨",
        mean2: "버텨",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Keep your chin up",
        mean: "턱을 위로 유지",
        mean2: "턱을 위로 유지",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "In the nick of time",
        mean: "간만에",
        mean2: "간만에",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "Don't count your chickens before they hatch",
        mean: "부화하기 전에 닭을 세지 마세요",
        mean2: "부화하기 전에 닭을 세지 마세요",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "Spill the beans",
        mean: "콩을 엎지르다",
        mean2: "콩을 엎지르다",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "Bite the bullet",
        mean: "총알을 깨물다",
        mean2: "총알을 깨물다",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "A penny for your thoughts",
        mean: "당신의 생각에 대한 페니",
        mean2: "당신의 생각에 대한 페니",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "Speak of the devil",
        mean: "악마에 대해 말하다",
        mean2: "악마에 대해 말하다",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "Bob's your uncle",
        mean: "Bob은 당신의 삼촌입니다.",
        mean2: "Bob은 당신의 삼촌입니다.",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "Easy as pie",
        mean: "파이처럼 쉬운",
        mean2: "파이처럼 쉬운",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "Hit the nail on the head",
        mean: "머리에 못을 박다",
        mean2: "머리에 못을 박다",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "Under the weather",
        mean: "날씨에 따라",
        mean2: "날씨에 따라",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "By the skin of your teeth",
        mean: "치아의 피부",
        mean2: "치아의 피부",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "Take it easy",
        mean: "진정해",
        mean2: "진정해",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "Call it a day",
        mean: "그만둬라",
        mean2: "그만둬라",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "A dime a dozen",
        mean: "한 푼도",
        mean2: "한 푼도",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "Mind your own business",
        mean: "자신의 일에 신경을 쓰십시오.",
        mean2: "자신의 일에 신경을 쓰십시오.",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "Better late than never",
        mean: "안 하는 것보다 늦게 하는 것이 낫다",
        mean2: "안 하는 것보다 늦게 하는 것이 낫다",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "The ball is in your court",
        mean: "공은 당신의 코트에 있습니다",
        mean2: "공은 당신의 코트에 있습니다",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "It's not rocket science",
        mean: "로켓 과학이 아니다",
        mean2: "로켓 과학이 아니다",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "You can say that again",
        mean: "다시 말해도 돼",
        mean2: "다시 말해도 돼",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Time flies",
        mean: "타임 플라이트",
        mean2: "타임 플라이트",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "What goes around comes around",
        mean: "돌아가는 것은 돌아간다",
        mean2: "돌아가는 것은 돌아간다",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "The apple of my eye",
        mean: "내 눈의 사과",
        mean2: "내 눈의 사과",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "The whole nine yards",
        mean: "9야드 전체",
        mean2: "9야드 전체",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Actions speak louder than words",
        mean: "말보다 행동이 더 중요하다",
        mean2: "말보다 행동이 더 중요하다",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "An arm and a leg",
        mean: "팔과 다리",
        mean2: "팔과 다리",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Don't judge a book by its cover",
        mean: "표지로 책을 판단하지 말라",
        mean2: "표지로 책을 판단하지 말라",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Every cloud has a silver lining",
        mean: "모든 구름에는 은색 안감이 있습니다.",
        mean2: "모든 구름에는 은색 안감이 있습니다.",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "The early bird catches the worm",
        mean: "일찍 일어나는 새가 벌레를 잡는다",
        mean2: "일찍 일어나는 새가 벌레를 잡는다",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Rome wasn't built in a day",
        mean: "로마는 하루아침에 이루어지지 않았다",
        mean2: "로마는 하루아침에 이루어지지 않았다",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Shake a leg",
        mean: "다리 흔들기",
        mean2: "다리 흔들기",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "A bird in the hand is worth two in the bush",
        mean: "손에 든 새 한 마리가 덤불 속에 있는 두 마리의 가치가 있다",
        mean2: "손에 든 새 한 마리가 덤불 속에 있는 두 마리의 가치가 있다",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Barking up the wrong tree",
        mean: "잘못된 나무를 짖다",
        mean2: "잘못된 나무를 짖다",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Curiosity killed the cat",
        mean: "호기심이 고양이를 죽였다",
        mean2: "호기심이 고양이를 죽였다",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Haste makes waste",
        mean: "서두름은 낭비를 만든다",
        mean2: "서두름은 낭비를 만든다",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "Ignorance is bliss",
        mean: "무지는 행복이다",
        mean2: "무지는 행복이다",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Jump on the bandwagon",
        mean: "시류에 편승",
        mean2: "시류에 편승",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Keep your eyes peeled",
        mean: "눈을 떼지 마십시오.",
        mean2: "눈을 떼지 마십시오.",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Let the cat out of the bag",
        mean: "가방에서 고양이를 꺼내십시오.",
        mean2: "가방에서 고양이를 꺼내십시오.",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Make a long story short",
        mean: "긴 이야기는 짧게",
        mean2: "긴 이야기는 짧게",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "No pain, no gain",
        mean: "고통이 없으면 얻는 것도 없다",
        mean2: "고통이 없으면 얻는 것도 없다",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "On cloud nine",
        mean: "온 클라우드 나인",
        mean2: "온 클라우드 나인",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Practice makes perfect",
        mean: "​​연습이 완벽을 만든다",
        mean2: "​​연습이 완벽을 만든다",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Saved by the bell",
        mean: "종소리로 저장",
        mean2: "종소리로 저장",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "The show must go on",
        mean: "쇼는 계속되어야 한다",
        mean2: "쇼는 계속되어야 한다",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Two heads are better than one",
        mean: "머리 둘이 하나보다 낫다",
        mean2: "머리 둘이 하나보다 낫다",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "You live and learn",
        mean: "당신은 살고 배운다",
        mean2: "당신은 살고 배운다",
        audio: "",
      },
    ],

    greeting: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Hello",
        mean: "안녕하세요",
        mean2: "안녕하세요",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Hi",
        mean: "안녕",
        mean2: "안녕",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Hey",
        mean: "이봐",
        mean2: "이봐",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Good morning",
        mean: "좋은 아침",
        mean2: "좋은 아침",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "Good afternoon",
        mean: "좋은 오후",
        mean2: "좋은 오후",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "Good evening",
        mean: "안녕히 주무세요",
        mean2: "안녕히 주무세요",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "How are you?",
        mean: "잘 지냈어?",
        mean2: "잘 지냈어?",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "How's it going?",
        mean: "어떻게 지내요?",
        mean2: "어떻게 지내요?",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "What's up?",
        mean: "무슨 일이야?",
        mean2: "무슨 일이야?",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "Long time no see",
        mean: "오랜만이야",
        mean2: "오랜만이야",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "Nice to see you",
        mean: "만나서 반갑습니다",
        mean2: "만나서 반갑습니다",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "It's a pleasure to meet you",
        mean: "만나서 반가워요",
        mean2: "만나서 반가워요",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "How have you been?",
        mean: "어떻게 지내셨어요?",
        mean2: "어떻게 지내셨어요?",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "How's everything?",
        mean: "다 어때요?",
        mean2: "다 어때요?",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "What have you been up to?",
        mean: "지금까지 무엇을 했습니까?",
        mean2: "지금까지 무엇을 했습니까?",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "Howdy",
        mean: "안녕",
        mean2: "안녕",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "Greetings",
        mean: "인사말",
        mean2: "인사말",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "Salutations",
        mean: "인사말",
        mean2: "인사말",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "What's new?",
        mean: "새로운 기능은 무엇입니까?",
        mean2: "새로운 기능은 무엇입니까?",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "How's your day going?",
        mean: "오늘 하루 어때?",
        mean2: "오늘 하루 어때?",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "How's your week been?",
        mean: "일주일은 어땠어?",
        mean2: "일주일은 어땠어?",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "Top of the morning to you",
        mean: "당신에게 아침의 탑",
        mean2: "당신에게 아침의 탑",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Welcome",
        mean: "환영합니다",
        mean2: "환영합니다",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Nice to meet you",
        mean: "만나서 반갑습니다",
        mean2: "만나서 반갑습니다",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Pleased to meet you",
        mean: "만나서 반가워요",
        mean2: "만나서 반가워요",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "What brings you here?",
        mean: "당신을 여기로 데려온 이유는 무엇입니까?",
        mean2: "당신을 여기로 데려온 이유는 무엇입니까?",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "Good to see you",
        mean: "만나서 반가워",
        mean2: "만나서 반가워",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Yo",
        mean: "요",
        mean2: "요",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "What's happening?",
        mean: "무슨 일이야?",
        mean2: "무슨 일이야?",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Good to meet you",
        mean: "만나서 반가워",
        mean2: "만나서 반가워",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Cheers",
        mean: "건배",
        mean2: "건배",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Sup",
        mean: "저녁",
        mean2: "저녁",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Hey there",
        mean: "안녕 거기",
        mean2: "안녕 거기",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Hiya",
        mean: "히야",
        mean2: "히야",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Good to see you again",
        mean: "다시 만나서 반가워",
        mean2: "다시 만나서 반가워",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Glad to see you",
        mean: "만나서 반가워",
        mean2: "만나서 반가워",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Fancy meeting you here",
        mean: "여기서 만나서 반가워",
        mean2: "여기서 만나서 반가워",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "How do you do?",
        mean: "어떻게 지내세요?",
        mean2: "어떻게 지내세요?",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "What's going on?",
        mean: "무슨 일이야?",
        mean2: "무슨 일이야?",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "How's life treating you?",
        mean: "삶이 당신을 어떻게 대하고 있습니까?",
        mean2: "삶이 당신을 어떻게 대하고 있습니까?",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "How's your family?",
        mean: "가족은 안녕하십니까?",
        mean2: "가족은 안녕하십니까?",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "How's work?",
        mean: "일은 어때?",
        mean2: "일은 어때?",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "What's happening in your world?",
        mean: "당신의 세계에서 무슨 일이 일어나고 있습니까?",
        mean2: "당신의 세계에서 무슨 일이 일어나고 있습니까?",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Hi-ya",
        mean: "하이야",
        mean2: "하이야",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Welcome back",
        mean: "다시 오신 것을 환영합니다",
        mean2: "다시 오신 것을 환영합니다",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Nice to run into you",
        mean: "​​만나서 반가워",
        mean2: "​​만나서 반가워",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "What a pleasant surprise",
        mean: "즐거운 놀라움",
        mean2: "즐거운 놀라움",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Happy to see you",
        mean: "만나서 반가워",
        mean2: "만나서 반가워",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Long time, no talk",
        mean: "오랜만에 노톡",
        mean2: "오랜만에 노톡",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "What's cooking?",
        mean: "요리는 무엇입니까?",
        mean2: "요리는 무엇입니까?",
        audio: "",
      },
    ],

    travel: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Destination",
        mean: "목적지",
        mean2: "목적지",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Journey",
        mean: "여행",
        mean2: "여행",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Trip",
        mean: "여행",
        mean2: "여행",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Vacation",
        mean: "휴가",
        mean2: "휴가",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "Tour",
        mean: "투어",
        mean2: "투어",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "Adventure",
        mean: "모험",
        mean2: "모험",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "Backpacking",
        mean: "배낭 여행",
        mean2: "배낭 여행",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "Cruise",
        mean: "크루즈",
        mean2: "크루즈",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "Flight",
        mean: "비행",
        mean2: "비행",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "Train",
        mean: "기차",
        mean2: "기차",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "Bus",
        mean: "버스",
        mean2: "버스",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "Car rental",
        mean: "렌터카",
        mean2: "렌터카",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "Accommodation",
        mean: "숙소",
        mean2: "숙소",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "Hotel",
        mean: "호텔",
        mean2: "호텔",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "Hostel",
        mean: "호스텔",
        mean2: "호스텔",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "Bed and breakfast",
        mean: "민박",
        mean2: "민박",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "Camping",
        mean: "캠핑",
        mean2: "캠핑",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "Sightseeing",
        mean: "관광",
        mean2: "관광",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "Tourist attraction",
        mean: "관광지",
        mean2: "관광지",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "Tour guide",
        mean: "투어 가이드",
        mean2: "투어 가이드",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "Passport",
        mean: "여권",
        mean2: "여권",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "Visa",
        mean: "비자",
        mean2: "비자",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Travel documents",
        mean: "여행 서류",
        mean2: "여행 서류",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Itinerary",
        mean: "여정",
        mean2: "여정",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Airport",
        mean: "공항",
        mean2: "공항",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "Boarding pass",
        mean: "탑승권",
        mean2: "탑승권",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "Customs",
        mean: "세관",
        mean2: "세관",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Security",
        mean: "보안",
        mean2: "보안",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "Luggage",
        mean: "수하물",
        mean2: "수하물",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Carry-on",
        mean: "기내 반입",
        mean2: "기내 반입",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Checked bag",
        mean: "위탁 수하물",
        mean2: "위탁 수하물",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Travel insurance",
        mean: "여행 보험",
        mean2: "여행 보험",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Currency exchange",
        mean: "환전",
        mean2: "환전",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Budget",
        mean: "예산",
        mean2: "예산",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Expense",
        mean: "경비",
        mean2: "경비",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Souvenir",
        mean: "기념품",
        mean2: "기념품",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Traveler's checks",
        mean: "여행자 수표",
        mean2: "여행자 수표",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Map",
        mean: "지도",
        mean2: "지도",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "GPS",
        mean: "GPS",
        mean2: "GPS",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Road trip",
        mean: "도로 여행",
        mean2: "도로 여행",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Beach",
        mean: "해변",
        mean2: "해변",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Mountain",
        mean: "산",
        mean2: "산",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Forest",
        mean: "숲",
        mean2: "숲",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Desert",
        mean: "사막",
        mean2: "사막",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Island",
        mean: "섬",
        mean2: "섬",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Urban",
        mean: "​​도시",
        mean2: "​​도시",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Rural",
        mean: "농촌",
        mean2: "농촌",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Historical",
        mean: "역사",
        mean2: "역사",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Natural",
        mean: "자연",
        mean2: "자연",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "Cultural",
        mean: "문화",
        mean2: "문화",
        audio: "",
      },
    ],

    numberAndMoney: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Dollar",
        mean: "달러",
        mean2: "달러",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Euro",
        mean: "유로",
        mean2: "유로",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Pound",
        mean: "파운드",
        mean2: "파운드",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Yen",
        mean: "엔",
        mean2: "엔",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "Rupee",
        mean: "루피",
        mean2: "루피",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "Currency",
        mean: "통화",
        mean2: "통화",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "Exchange rate",
        mean: "환율",
        mean2: "환율",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "Bank",
        mean: "은행",
        mean2: "은행",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "ATM",
        mean: "ATM",
        mean2: "ATM",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "Credit card",
        mean: "신용카드",
        mean2: "신용카드",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "Debit card",
        mean: "체크카드",
        mean2: "체크카드",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "Cash",
        mean: "현금",
        mean2: "현금",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "Check",
        mean: "확인",
        mean2: "확인",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "Deposit",
        mean: "보증금",
        mean2: "보증금",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "Withdrawal",
        mean: "철회",
        mean2: "철회",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "Balance",
        mean: "균형",
        mean2: "균형",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "Interest",
        mean: "이자",
        mean2: "이자",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "Loan",
        mean: "대출",
        mean2: "대출",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "Mortgage",
        mean: "모기지",
        mean2: "모기지",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "Investment",
        mean: "투자",
        mean2: "투자",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "Stocks",
        mean: "주식",
        mean2: "주식",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "Bonds",
        mean: "채권",
        mean2: "채권",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Dividend",
        mean: "배당금",
        mean2: "배당금",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Capital",
        mean: "자본금",
        mean2: "자본금",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Profit",
        mean: "이익",
        mean2: "이익",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "Loss",
        mean: "손실",
        mean2: "손실",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "Revenue",
        mean: "수익",
        mean2: "수익",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Expenses",
        mean: "비용",
        mean2: "비용",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "Budget",
        mean: "예산",
        mean2: "예산",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Income",
        mean: "소득",
        mean2: "소득",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Tax",
        mean: "세금",
        mean2: "세금",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Deduction",
        mean: "공제",
        mean2: "공제",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Refund",
        mean: "환불",
        mean2: "환불",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Gross",
        mean: "총",
        mean2: "총",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Net",
        mean: "순",
        mean2: "순",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Inflation",
        mean: "인플레이션",
        mean2: "인플레이션",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Deflation",
        mean: "디플레이션",
        mean2: "디플레이션",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Price",
        mean: "가격",
        mean2: "가격",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "Cost",
        mean: "비용",
        mean2: "비용",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Market",
        mean: "시장",
        mean2: "시장",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Supply",
        mean: "공급",
        mean2: "공급",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Demand",
        mean: "수요",
        mean2: "수요",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Asset",
        mean: "자산",
        mean2: "자산",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Liability",
        mean: "책임",
        mean2: "책임",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Equity",
        mean: "형평성",
        mean2: "형평성",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Audit",
        mean: "​​감사",
        mean2: "​​감사",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Accounting",
        mean: "회계",
        mean2: "회계",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Payroll",
        mean: "급여",
        mean2: "급여",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Retirement",
        mean: "은퇴",
        mean2: "은퇴",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "Savings",
        mean: "저축",
        mean2: "저축",
        audio: "",
      },
    ],

    location: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Address",
        mean: "주소",
        mean2: "주소",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Location",
        mean: "위치",
        mean2: "위치",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Place",
        mean: "장소",
        mean2: "장소",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Area",
        mean: "면적",
        mean2: "면적",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "Neighborhood",
        mean: "이웃",
        mean2: "이웃",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "City",
        mean: "도시",
        mean2: "도시",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "Town",
        mean: "마을",
        mean2: "마을",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "Village",
        mean: "마을",
        mean2: "마을",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "Country",
        mean: "국가",
        mean2: "국가",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "State",
        mean: "상태",
        mean2: "상태",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "Province",
        mean: "지방",
        mean2: "지방",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "Region",
        mean: "지역",
        mean2: "지역",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "District",
        mean: "지구",
        mean2: "지구",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "Zone",
        mean: "구역",
        mean2: "구역",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "Street",
        mean: "거리",
        mean2: "거리",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "Road",
        mean: "도로",
        mean2: "도로",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "Highway",
        mean: "고속도로",
        mean2: "고속도로",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "Lane",
        mean: "레인",
        mean2: "레인",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "Boulevard",
        mean: "대로",
        mean2: "대로",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "Avenue",
        mean: "애비뉴",
        mean2: "애비뉴",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "Square",
        mean: "광장",
        mean2: "광장",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "Park",
        mean: "공원",
        mean2: "공원",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Garden",
        mean: "정원",
        mean2: "정원",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Beach",
        mean: "해변",
        mean2: "해변",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Mountain",
        mean: "산",
        mean2: "산",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "Valley",
        mean: "계곡",
        mean2: "계곡",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "River",
        mean: "강",
        mean2: "강",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Lake",
        mean: "호수",
        mean2: "호수",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "Ocean",
        mean: "바다",
        mean2: "바다",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Sea",
        mean: "바다",
        mean2: "바다",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Island",
        mean: "섬",
        mean2: "섬",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Peninsula",
        mean: "반도",
        mean2: "반도",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Desert",
        mean: "사막",
        mean2: "사막",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Forest",
        mean: "숲",
        mean2: "숲",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Jungle",
        mean: "정글",
        mean2: "정글",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Savanna",
        mean: "사바나",
        mean2: "사바나",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Tundra",
        mean: "툰드라",
        mean2: "툰드라",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Arctic",
        mean: "북극",
        mean2: "북극",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "Antarctic",
        mean: "남극",
        mean2: "남극",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Hemisphere",
        mean: "반구",
        mean2: "반구",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Equator",
        mean: "적도",
        mean2: "적도",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Latitude",
        mean: "위도",
        mean2: "위도",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Longitude",
        mean: "경도",
        mean2: "경도",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Altitude",
        mean: "고도",
        mean2: "고도",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Elevation",
        mean: "표고",
        mean2: "표고",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Hill",
        mean: "​​언덕",
        mean2: "​​언덕",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Mountain range",
        mean: "산맥",
        mean2: "산맥",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Canyon",
        mean: "협곡",
        mean2: "협곡",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Gorge",
        mean: "협곡",
        mean2: "협곡",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "Cavern",
        mean: "동굴",
        mean2: "동굴",
        audio: "",
      },
    ],

    timeAndDate: [
      {
        seq: 1,
        isLearning: false,
        isFavorite: false,
        word: "Second",
        mean: "초",
        mean2: "초",
        audio: "",
      },
      {
        seq: 2,
        isLearning: false,
        isFavorite: false,
        word: "Minute",
        mean: "분",
        mean2: "분",
        audio: "",
      },
      {
        seq: 3,
        isLearning: false,
        isFavorite: false,
        word: "Hour",
        mean: "시간",
        mean2: "시간",
        audio: "",
      },
      {
        seq: 4,
        isLearning: false,
        isFavorite: false,
        word: "Day",
        mean: "일",
        mean2: "일",
        audio: "",
      },
      {
        seq: 5,
        isLearning: false,
        isFavorite: false,
        word: "Week",
        mean: "주",
        mean2: "주",
        audio: "",
      },
      {
        seq: 6,
        isLearning: false,
        isFavorite: false,
        word: "Month",
        mean: "월",
        mean2: "월",
        audio: "",
      },
      {
        seq: 7,
        isLearning: false,
        isFavorite: false,
        word: "Year",
        mean: "연도",
        mean2: "연도",
        audio: "",
      },
      {
        seq: 8,
        isLearning: false,
        isFavorite: false,
        word: "Decade",
        mean: "년",
        mean2: "년",
        audio: "",
      },
      {
        seq: 9,
        isLearning: false,
        isFavorite: false,
        word: "Century",
        mean: "세기",
        mean2: "세기",
        audio: "",
      },
      {
        seq: 10,
        isLearning: false,
        isFavorite: false,
        word: "Millennium",
        mean: "밀레니엄",
        mean2: "밀레니엄",
        audio: "",
      },
      {
        seq: 11,
        isLearning: false,
        isFavorite: false,
        word: "January",
        mean: "1월",
        mean2: "1월",
        audio: "",
      },
      {
        seq: 12,
        isLearning: false,
        isFavorite: false,
        word: "February",
        mean: "2월",
        mean2: "2월",
        audio: "",
      },
      {
        seq: 13,
        isLearning: false,
        isFavorite: false,
        word: "March",
        mean: "3월",
        mean2: "3월",
        audio: "",
      },
      {
        seq: 14,
        isLearning: false,
        isFavorite: false,
        word: "April",
        mean: "4월",
        mean2: "4월",
        audio: "",
      },
      {
        seq: 15,
        isLearning: false,
        isFavorite: false,
        word: "May",
        mean: "5월",
        mean2: "5월",
        audio: "",
      },
      {
        seq: 16,
        isLearning: false,
        isFavorite: false,
        word: "June",
        mean: "6월",
        mean2: "6월",
        audio: "",
      },
      {
        seq: 17,
        isLearning: false,
        isFavorite: false,
        word: "July",
        mean: "7월",
        mean2: "7월",
        audio: "",
      },
      {
        seq: 18,
        isLearning: false,
        isFavorite: false,
        word: "August",
        mean: "8월",
        mean2: "8월",
        audio: "",
      },
      {
        seq: 19,
        isLearning: false,
        isFavorite: false,
        word: "September",
        mean: "9월",
        mean2: "9월",
        audio: "",
      },
      {
        seq: 20,
        isLearning: false,
        isFavorite: false,
        word: "October",
        mean: "10월",
        mean2: "10월",
        audio: "",
      },
      {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "November",
        mean: "11월",
        mean2: "11월",
        audio: "",
      },
      {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "December",
        mean: "12월",
        mean2: "12월",
        audio: "",
      },
      {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Monday",
        mean: "월요일",
        mean2: "월요일",
        audio: "",
      },
      {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Tuesday",
        mean: "화요일",
        mean2: "화요일",
        audio: "",
      },
      {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Wednesday",
        mean: "수요일",
        mean2: "수요일",
        audio: "",
      },
      {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "Thursday",
        mean: "목요일",
        mean2: "목요일",
        audio: "",
      },
      {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "Friday",
        mean: "금요일",
        mean2: "금요일",
        audio: "",
      },
      {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Saturday",
        mean: "토요일",
        mean2: "토요일",
        audio: "",
      },
      {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "Sunday",
        mean: "일요일",
        mean2: "일요일",
        audio: "",
      },
      {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Weekend",
        mean: "주말",
        mean2: "주말",
        audio: "",
      },
      {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Weekday",
        mean: "평일",
        mean2: "평일",
        audio: "",
      },
      {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Yesterday",
        mean: "어제",
        mean2: "어제",
        audio: "",
      },
      {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Today",
        mean: "오늘",
        mean2: "오늘",
        audio: "",
      },
      {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Tomorrow",
        mean: "내일",
        mean2: "내일",
        audio: "",
      },
      {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Dawn",
        mean: "새벽",
        mean2: "새벽",
        audio: "",
      },
      {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Morning",
        mean: "아침",
        mean2: "아침",
        audio: "",
      },
      {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Noon",
        mean: "정오",
        mean2: "정오",
        audio: "",
      },
      {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Afternoon",
        mean: "오후",
        mean2: "오후",
        audio: "",
      },
      {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "Evening",
        mean: "저녁",
        mean2: "저녁",
        audio: "",
      },
      {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Night",
        mean: "밤",
        mean2: "밤",
        audio: "",
      },
      {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Midnight",
        mean: "자정",
        mean2: "자정",
        audio: "",
      },
      {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Calendar",
        mean: "달력",
        mean2: "달력",
        audio: "",
      },
      {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Clock",
        mean: "시계",
        mean2: "시계",
        audio: "",
      },
      {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Stopwatch",
        mean: "스톱워치",
        mean2: "스톱워치",
        audio: "",
      },
      {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Timer",
        mean: "타이머",
        mean2: "타이머",
        audio: "",
      },
      {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Time zone",
        mean: "​​시간대",
        mean2: "​​시간대",
        audio: "",
      },
      {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Date",
        mean: "날짜",
        mean2: "날짜",
        audio: "",
      },
      {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Anniversary",
        mean: "기념일",
        mean2: "기념일",
        audio: "",
      },
      {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Birthday",
        mean: "생일",
        mean2: "생일",
        audio: "",
      },
      {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "Age",
        mean: "나이",
        mean2: "나이",
        audio: "",
      },
    ],
  },
];
