export const learningData: { seq:number;isLearning:boolean;isFavorite:boolean; word:string; mean: string; mean2:string ; audio:string}[] = [
    {
        seq:1,
        isLearning: false,
        isFavorite:false,
        word:'Chit-chat',
        mean:'Chit-chat',
        mean2:'Chit-chat',
        audio:''
    },
    {
        seq:2,
        isLearning: false,
        isFavorite: false,
        word: 'Small talk',
        mean: '작은 대화',
        mean2: '작은 대화',
        audio: ''
    },
    {
        seq:3,
        isLearning: false,
        isFavorite: false,
        word: 'Catch up',
        mean: '따라 잡으십시오',
        mean2: '따라 잡으십시오',
        audio: ''
    },
    {
        seq:4,
        isLearning: false,
        isFavorite: false,
        word: 'Hang out',
        mean: '어울리십시오',
        mean2: '어울리십시오',
        audio: ''
    },
    {
        seq:5,
        isLearning: false,
        isFavorite: false,
        word: 'Chill out',
        mean: '식히십시오',
        mean2: '식히십시오',
        audio: ''
    },
    {
        seq:6,
        isLearning: false,
        isFavorite: false,
        word: 'Cheer up',
        mean: '환호하십시오',
        mean2: '환호하십시오',
        audio: ''
    },
    {
        seq:7,
        isLearning: false,
        isFavorite: false,
        word: 'Keep in touch',
        mean: '연락을 유지하십시오',
        mean2: '연락을 유지하십시오',
        audio: ''
    },
    {
        seq:8,
        isLearning: false,
        isFavorite: false,
        word: 'Take it easy',
        mean: '쉽게 가져 가십시오',
        mean2: '쉽게 가져 가십시오',
        audio: ''
    },
    {
        seq:9,
        isLearning: false,
        isFavorite: false,
        word: 'Get together',
        mean: '함께 모이십시오',
        mean2: '함께 모이십시오',
        audio: ''
    },
    {
        seq:10,
        isLearning: false,
        isFavorite: false,
        word: 'Call it a day',
        mean: '그것을 하루라고 부릅니다',
        mean2: '그것을 하루라고 부릅니다',
        audio: ''
    },
    {
        seq:11,
        isLearning: false,
        isFavorite:false,
        word:'Metropolis',
        mean:'대도시',
        mean2:'대도시',
        audio:''
    },
    {
        seq:12,
        isLearning: false,
        isFavorite: false,
        word: 'Countryside',
        mean: '시골',
        mean2: '시골',
        audio: ''
    },
    {
        seq:13,
        isLearning: false,
        isFavorite: false,
        word: 'Suburb',
        mean: '교외',
        mean2: '교외',
        audio: ''
    },
    {
        seq:14,
        isLearning: false,
        isFavorite: false,
        word: 'Seaside',
        mean: '해변',
        mean2: '해변',
        audio: ''
    },
    {
        seq:15,
        isLearning: false,
        isFavorite: false,
        word: 'Mountainous',
        mean: '산악',
        mean2: '산악',
        audio: ''
    },
    {
        seq:16,
        isLearning: false,
        isFavorite: false,
        word: 'Deserted',
        mean: '황폐',
        mean2: '황폐',
        audio: ''
    },
    {
        seq:17,
        isLearning: false,
        isFavorite: false,
        word: 'Coastal',
        mean: '해안',
        mean2: '해안',
        audio: ''
    },
    {
        seq:18,
        isLearning: false,
        isFavorite: false,
        word: 'Urban',
        mean: '도시',
        mean2: '도시',
        audio: ''
    },
    {
        seq:19,
        isLearning: false,
        isFavorite: false,
        word: 'Rural',
        mean: '농촌',
        mean2: '농촌',
        audio: ''
    },
    {
        seq:20,
        isLearning: false,
        isFavorite: false,
        word: 'Islandic',
        mean: '섬',
        mean2: '섬',
        audio: ''
    },



    {
        seq: 21,
        isLearning: false,
        isFavorite: false,
        word: "Voicemail",
        mean: "음성 메일",
        mean2: "",
        audio: "",
    },
    {
        seq: 22,
        isLearning: false,
        isFavorite: false,
        word: "Spam",
        mean: "스팸",
        mean2: "",
        audio: "",
    },
    {
        seq: 23,
        isLearning: false,
        isFavorite: false,
        word: "Router",
        mean: "라우터",
        mean2: "",
        audio: "",
    },
    {
        seq: 24,
        isLearning: false,
        isFavorite: false,
        word: "Hotspot",
        mean: "핫스팟",
        mean2: "",
        audio: "",
    },
    {
        seq: 25,
        isLearning: false,
        isFavorite: false,
        word: "Emoji",
        mean: "이모티콘",
        mean2: "",
        audio: "",
    },
    {
        seq: 26,
        isLearning: false,
        isFavorite: false,
        word: "Attachment",
        mean: "첨부 파일",
        mean2: "",
        audio: "",
    },
    {
        seq: 27,
        isLearning: false,
        isFavorite: false,
        word: "Browser",
        mean: "브라우저",
        mean2: "",
        audio: "",
    },
    {
        seq: 28,
        isLearning: false,
        isFavorite: false,
        word: "Megabyte",
        mean: "메가 바이트",
        mean2: "",
        audio: "",
    },
    {
        seq: 29,
        isLearning: false,
        isFavorite: false,
        word: "Caller ID",
        mean: "발신자 ID",
        mean2: "",
        audio: "",
    },
    {
        seq: 30,
        isLearning: false,
        isFavorite: false,
        word: "Firewall",
        mean: "방화벽",
        mean2: "",
        audio: "",
    },

    {
        seq: 31,
        isLearning: false,
        isFavorite: false,
        word: "Hello",
        mean: "안녕하세요",
        mean2: "",
        audio: "",
    },
    {
        seq: 32,
        isLearning: false,
        isFavorite: false,
        word: "Hi",
        mean: "안녕하세요",
        mean2: "",
        audio: "",
    },
    {
        seq: 33,
        isLearning: false,
        isFavorite: false,
        word: "Hey",
        mean: "이봐",
        mean2: "",
        audio: "",
    },
    {
        seq: 34,
        isLearning: false,
        isFavorite: false,
        word: "Good morning",
        mean: "좋은 아침",
        mean2: "",
        audio: "",
    },
    {
        seq: 35,
        isLearning: false,
        isFavorite: false,
        word: "Good afternoon",
        mean: "좋은 오후",
        mean2: "",
        audio: "",
    },
    {
        seq: 36,
        isLearning: false,
        isFavorite: false,
        word: "Good evening",
        mean: "좋은 저녁",
        mean2: "",
        audio: "",
    },
    {
        seq: 37,
        isLearning: false,
        isFavorite: false,
        word: "Greetings",
        mean: "인사",
        mean2: "",
        audio: "",
    },
    {
        seq: 38,
        isLearning: false,
        isFavorite: false,
        word: "Salutations",
        mean: "경례",
        mean2: "",
        audio: "",
    },
    {
        seq: 39,
        isLearning: false,
        isFavorite: false,
        word: "Howdy",
        mean: "Howdy",
        mean2: "",
        audio: "",
    },
    {
        seq: 40,
        isLearning: false,
        isFavorite: false,
        word: "Yo",
        mean: "요",
        mean2: "",
        audio: "",
    },
    {
        seq: 41,
        isLearning: false,
        isFavorite: false,
        word: "Quest",
        mean: "퀘스트",
        mean2: "",
        audio: "",
    },
    {
        seq: 42,
        isLearning: false,
        isFavorite: false,
        word: "Power-up",
        mean: "파워 업",
        mean2: "",
        audio: "",
    },
    {
        seq: 43,
        isLearning: false,
        isFavorite: false,
        word: "Multiplayer",
        mean: "멀티 플레이어",
        mean2: "",
        audio: "",
    },
    {
        seq: 44,
        isLearning: false,
        isFavorite: false,
        word: "Boss battle",
        mean: "보스 전투",
        mean2: "",
        audio: "",
    },
    {
        seq: 45,
        isLearning: false,
        isFavorite: false,
        word: "Inventory",
        mean: "재고",
        mean2: "",
        audio: "",
    },
    {
        seq: 46,
        isLearning: false,
        isFavorite: false,
        word: "Cutscene",
        mean: "컷신",
        mean2: "",
        audio: "",
    },
    {
        seq: 47,
        isLearning: false,
        isFavorite: false,
        word: "Health bar",
        mean: "건강 막대",
        mean2: "",
        audio: "",
    },
    {
        seq: 48,
        isLearning: false,
        isFavorite: false,
        word: "Save point",
        mean: "포인트를 저장하십시오",
        mean2: "",
        audio: "",
    },
    {
        seq: 49,
        isLearning: false,
        isFavorite: false,
        word: "Side quest",
        mean: "사이드 퀘스트",
        mean2: "",
        audio: "",
    },
    {
        seq: 50,
        isLearning: false,
        isFavorite: false,
        word: "Game over",
        mean: "게임 오버",
        mean2: "",
        audio: "",
    }
]