//5급
export const data5 = [
    {
        noun : [
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가게',
                mean: 'store',
                mean2: 'store',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가곡',
                mean: 'song',
                mean2: 'song',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가공',
                mean: 'Processing',
                mean2: 'Processing',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가구',
                mean: 'Furniture',
                mean2: 'Furniture',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가닥',
                mean: 'piece',
                mean2: 'piece',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가로수',
                mean: 'colonnade',
                mean2: 'colonnade',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가면',
                mean: 'mask',
                mean2: 'mask',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '가문',
                mean: 'droughty',
                mean2: 'droughty',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '가사',
                mean: 'Lyrics',
                mean2: 'Lyrics',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '가속화',
                mean: 'Acceleration',
                mean2: 'Acceleration',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '가시',
                mean: 'Thorn',
                mean2: 'Thorn',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '가야금',
                mean: 'Gayageum',
                mean2: 'Gayageum',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '가옥',
                mean: 'premises',
                mean2: 'premises',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '가요계',
                mean: 'Song',
                mean2: 'Song',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '가장자리',
                mean: 'edge',
                mean2: 'edge',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '가중',
                mean: 'Aggression',
                mean2: 'Aggression',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '가창력',
                mean: 'Singing power',
                mean2: 'Singing power',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '가축',
                mean: 'Livestock',
                mean2: 'Livestock',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '가해자',
                mean: 'attacker',
                mean2: 'attacker',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '각광',
                mean: 'footlights',
                mean2: 'footlights',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '각지',
                mean: 'All places',
                mean2: 'All places',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '간접',
                mean: 'Indirect',
                mean2: 'Indirect',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '간직00',
                mean: 'Legend 00',
                mean2: 'Legend 00',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '갈대',
                mean: 'Reed',
                mean2: 'Reed',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '감격',
                mean: 'effervescence',
                mean2: 'effervescence',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '감사',
                mean: 'Thanks',
                mean2: 'Thanks',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '감상',
                mean: 'Appreciation',
                mean2: 'Appreciation',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '감성',
                mean: 'Emotion',
                mean2: 'Emotion',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '감염',
                mean: 'infection',
                mean2: 'infection',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '감탄',
                mean: 'Admiration',
                mean2: 'Admiration',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '감탄사',
                mean: 'interjection',
                mean2: 'interjection',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '갑',
                mean: 'A',
                mean2: 'A',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '강국',
                mean: 'Power',
                mean2: 'Power',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '강당',
                mean: 'auditorium',
                mean2: 'auditorium',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '강대국',
                mean: 'Great power',
                mean2: 'Great power',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '강도',
                mean: 'Strength',
                mean2: 'Strength',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '강력00',
                mean: 'Strong 00',
                mean2: 'Strong 00',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '강산',
                mean: 'Gangsan',
                mean2: 'Gangsan',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '강연',
                mean: 'lecture',
                mean2: 'lecture',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '강우량',
                mean: 'fall',
                mean2: 'fall',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '강자',
                mean: 'Stronger',
                mean2: 'Stronger',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '강좌',
                mean: 'lecture',
                mean2: 'lecture',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '강풍',
                mean: 'gale',
                mean2: 'gale',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '강화',
                mean: 'enforce',
                mean2: 'enforce',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '개강',
                mean: 'Starting',
                mean2: 'Starting',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '개개인',
                mean: 'Individual',
                mean2: 'Individual',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '개막식',
                mean: 'Opening ceremony',
                mean2: 'Opening ceremony',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '개봉',
                mean: 'release',
                mean2: 'release',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '개설',
                mean: 'Opening',
                mean2: 'Opening',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '개수',
                mean: 'Count',
                mean2: 'Count',
                audio: '',
            },
        ],
        verb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가리다',
                mean: 'Call',
                mean2: 'Call',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가시다',
                mean: 'Go',
                mean2: 'Go',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '갈다',
                mean: 'Go',
                mean2: 'Go',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '감기다',
                mean: 'Cold',
                mean2: 'Cold',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '거느리다',
                mean: 'Be',
                mean2: 'Be',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '거닐다',
                mean: 'walk',
                mean2: 'walk',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '걷어차다',
                mean: 'Kick',
                mean2: 'Kick',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '겁내다',
                mean: 'funk',
                mean2: 'funk',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '겸하다',
                mean: 'combine',
                mean2: 'combine',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '고이다',
                mean: 'Go',
                mean2: 'Go',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '관련짓다',
                mean: 'Relate',
                mean2: 'Relate',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '관하다',
                mean: 'Tear',
                mean2: 'Tear',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '구겨지다',
                mean: 'Crumple',
                mean2: 'Crumple',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '구르다',
                mean: 'Roll',
                mean2: 'Roll',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '굳히다',
                mean: 'bind',
                mean2: 'bind',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '굴러가다',
                mean: 'Roll',
                mean2: 'Roll',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '그리다',
                mean: 'Draw',
                mean2: 'Draw',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '기하다',
                mean: 'Decorate',
                mean2: 'Decorate',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '깜짝하다',
                mean: 'Surprise',
                mean2: 'Surprise',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '꺼지다',
                mean: 'Turn off',
                mean2: 'Turn off',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '꺾이다',
                mean: 'break',
                mean2: 'break',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '꼬다',
                mean: 'twist',
                mean2: 'twist',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '꾸짖다',
                mean: 'scold',
                mean2: 'scold',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '꿰매다',
                mean: 'darn',
                mean2: 'darn',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '끄집어내다',
                mean: 'Pull out',
                mean2: 'Pull out',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '끊이다',
                mean: 'Break',
                mean2: 'Break',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '끌어내다',
                mean: 'Pull out',
                mean2: 'Pull out',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '끌어들이다',
                mean: 'Drag',
                mean2: 'Drag',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '끌어올리다',
                mean: 'Pull up',
                mean2: 'Pull up',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '끝맺다',
                mean: 'End',
                mean2: 'End',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '나돌다',
                mean: 'Turn out',
                mean2: 'Turn out',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '낚다',
                mean: 'fish',
                mean2: 'fish',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '날아들다',
                mean: 'Fly',
                mean2: 'Fly',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '날아오르다',
                mean: 'Flap',
                mean2: 'Flap',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '내딛다',
                mean: 'Take',
                mean2: 'Take',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '내리치다',
                mean: 'Fall',
                mean2: 'Fall',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '내뱉다',
                mean: 'spit out',
                mean2: 'spit out',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '내보이다',
                mean: 'Me',
                mean2: 'Me',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '내비치다',
                mean: 'Show off',
                mean2: 'Show off',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '내쉬다',
                mean: 'exhale',
                mean2: 'exhale',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '내오다',
                mean: 'Come out',
                mean2: 'Come out',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '내지르다',
                mean: 'Put up',
                mean2: 'Put up',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '놓아주다',
                mean: 'Let',
                mean2: 'Let',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '누다',
                mean: 'Go',
                mean2: 'Go',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '누리다',
                mean: 'Never',
                mean2: 'Never',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '눈치채다00',
                mean: 'Notice 00',
                mean2: 'Notice 00',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '눌리다',
                mean: 'Press',
                mean2: 'Press',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '뉘우치다',
                mean: 'Regret',
                mean2: 'Regret',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '늘어지다',
                mean: 'Tap',
                mean2: 'Tap',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '다다르다',
                mean: 'Reach',
                mean2: 'Reach',
                audio: '',
            },
        ],
        adjective:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가느다랗다',
                mean: 'Thin',
                mean2: 'Thin',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '간결하다',
                mean: 'Be concise',
                mean2: 'Be concise',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '간소하다',
                mean: 'Simplify',
                mean2: 'Simplify',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '감미롭다',
                mean: 'Sweet',
                mean2: 'Sweet',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '갑갑하다',
                mean: 'Cramp',
                mean2: 'Cramp',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '값지다',
                mean: 'Pay',
                mean2: 'Pay',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '강렬하다',
                mean: 'Be intense',
                mean2: 'Be intense',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '거세다',
                mean: 'Rende',
                mean2: 'Rende',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '격렬하다',
                mean: 'Be intense',
                mean2: 'Be intense',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '경솔하다',
                mean: 'Rash',
                mean2: 'Rash',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '경쾌하다',
                mean: 'Be cheerful',
                mean2: 'Be cheerful',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '고단하다',
                mean: 'Be hard',
                mean2: 'Be hard',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '고르다',
                mean: 'Choose',
                mean2: 'Choose',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '고상하다',
                mean: 'Groan',
                mean2: 'Groan',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '고생스럽다',
                mean: 'Troubled',
                mean2: 'Troubled',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '공평하다',
                mean: 'Fair',
                mean2: 'Fair',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '과감하다',
                mean: 'Bold',
                mean2: 'Bold',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '과도하다',
                mean: 'Overdose',
                mean2: 'Overdose',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '과하다',
                mean: 'Excessive',
                mean2: 'Excessive',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '관대하다',
                mean: 'Tolerant',
                mean2: 'Tolerant',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '극심하다',
                mean: 'Be extreme',
                mean2: 'Be extreme',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '근사하다',
                mean: 'Nest',
                mean2: 'Nest',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '급격하다',
                mean: 'Rash',
                mean2: 'Rash',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '기름지다',
                mean: 'Oily',
                mean2: 'Oily',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '기막히다',
                mean: 'Amazing',
                mean2: 'Amazing',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '기발하다',
                mean: 'Quirky',
                mean2: 'Quirky',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '끔찍하다',
                mean: 'Horrible',
                mean2: 'Horrible',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '남다르다',
                mean: 'Remain',
                mean2: 'Remain',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '납작하다',
                mean: 'Flatten',
                mean2: 'Flatten',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '낯익다',
                mean: 'Familiar',
                mean2: 'Familiar',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '네모나다',
                mean: 'Square',
                mean2: 'Square',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '누렇다',
                mean: 'Yellow',
                mean2: 'Yellow',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '능숙하다',
                mean: 'be good at',
                mean2: 'be good at',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '다급하다',
                mean: 'Be in urgent',
                mean2: 'Be in urgent',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '단조롭다',
                mean: 'Monotonize',
                mean2: 'Monotonize',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '대견하다',
                mean: 'Confront',
                mean2: 'Confront',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '덜하다',
                mean: 'Be less',
                mean2: 'Be less',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '두텁다',
                mean: 'Be thick',
                mean2: 'Be thick',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '둔하다',
                mean: 'Dull',
                mean2: 'Dull',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '따갑다',
                mean: 'Tingle',
                mean2: 'Tingle',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '떫다',
                mean: 'Stumble',
                mean2: 'Stumble',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '떳떳하다',
                mean: 'Be proud',
                mean2: 'Be proud',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '또렷하다',
                mean: 'Clear',
                mean2: 'Clear',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '뜸하다',
                mean: 'Moxibute',
                mean2: 'Moxibute',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '막막하다',
                mean: "It's dead ",
                mean2: "It's dead ",
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '매끄럽다',
                mean: 'Smooth',
                mean2: 'Smooth',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '매섭다',
                mean: 'Stumble',
                mean2: 'Stumble',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '매콤하다',
                mean: 'Spicy',
                mean2: 'Spicy',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '머지않다',
                mean: 'Soon',
                mean2: 'Soon',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '먹음직스럽다',
                mean: "It's delicious",
                mean2: "It's delicious",
                audio: '',
            },
        ],
        adverb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가지런히',
                mean: 'Neatly',
                mean2: 'Neatly',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '간간이',
                mean: 'Occasional',
                mean2: 'Occasional',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '간절히',
                mean: 'desperately',
                mean2: 'desperately',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '강력히',
                mean: 'Strongly',
                mean2: 'Strongly',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '그리',
                mean: 'So',
                mean2: 'So',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '그리하여',
                mean: 'therefore',
                mean2: 'therefore',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '금세',
                mean: 'Quickly',
                mean2: 'Quickly',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '까딱',
                mean: 'Crap',
                mean2: 'Crap',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '깡충깡충',
                mean: 'Gap',
                mean2: 'Gap',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '꼬르륵',
                mean: 'Color',
                mean2: 'Color',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '꼬박',
                mean: 'Cool',
                mean2: 'Cool',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '꼬박꼬박',
                mean: 'Pour',
                mean2: 'Pour',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '꼭꼭',
                mean: 'Just',
                mean2: 'Just',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '꼼짝없이',
                mean: 'Stagnantly',
                mean2: 'Stagnantly',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '꽁꽁',
                mean: 'Cord',
                mean2: 'Cord',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '꾸벅꾸벅',
                mean: 'Cut',
                mean2: 'Cut',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '나날이',
                mean: 'Day',
                mean2: 'Day',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '날로',
                mean: 'Day',
                mean2: 'Day',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '남몰래',
                mean: 'secretly',
                mean2: 'secretly',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '다름없이',
                mean: 'Likely',
                mean2: 'Likely',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '단',
                mean: 'Only',
                mean2: 'Only',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '대대로',
                mean: 'From generation to generation',
                mean2: 'From generation to generation',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '더없이',
                mean: 'So much',
                mean2: 'So much',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '동동',
                mean: 'Dongdong',
                mean2: 'Dongdong',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '듬뿍',
                mean: 'brimfully',
                mean2: 'brimfully',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '딱',
                mean: 'Just',
                mean2: 'Just',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '떡',
                mean: 'Rice cake',
                mean2: 'Rice cake',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '똑00',
                mean: 'Dart00',
                mean2: 'Dart00',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '똑똑',
                mean: 'smart',
                mean2: 'smart',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '뚜렷이',
                mean: 'in evidence',
                mean2: 'in evidence',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '뚝',
                mean: 'Tuk',
                mean2: 'Tuk',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '뚝뚝',
                mean: 'Tak',
                mean2: 'Tak',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '마저',
                mean: 'Even',
                mean2: 'Even',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '멍하니',
                mean: 'blankly',
                mean2: 'blankly',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '명백히',
                mean: 'overtly',
                mean2: 'overtly',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '명확히',
                mean: 'clearly',
                mean2: 'clearly',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '모조리',
                mean: 'all',
                mean2: 'all',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '무심코',
                mean: 'Unintentionally',
                mean2: 'Unintentionally',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '밤낮없이',
                mean: 'Day and night',
                mean2: 'Day and night',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '버럭',
                mean: 'Crowd',
                mean2: 'Crowd',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '번번이',
                mean: 'Turn',
                mean2: 'Turn',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '변함없이',
                mean: 'Unchanged',
                mean2: 'Unchanged',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '보글보글',
                mean: 'Boggle',
                mean2: 'Boggle',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '부쩍',
                mean: 'Surrender',
                mean2: 'Surrender',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '불행히',
                mean: 'Unfortunately',
                mean2: 'Unfortunately',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '뻘뻘',
                mean: 'Pung',
                mean2: 'Pung',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '살금살금',
                mean: 'Sneaking',
                mean2: 'Sneaking',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '살며시',
                mean: 'Gently',
                mean2: 'Gently',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '설사',
                mean: 'Diarrhea',
                mean2: 'Diarrhea',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '성실히',
                mean: 'Faithfully',
                mean2: 'Faithfully',
                audio: '',
            },
        ],
    }
];

//6급

export const data6 = [
    {
        noun : [
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가계',
                mean: 'Household',
                mean2: 'Household',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가늠',
                mean: 'Measure',
                mean2: 'Measure',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가담',
                mean: 'partisanship',
                mean2: 'partisanship',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가동',
                mean: 'behavior',
                mean2: 'behavior',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가르침',
                mean: 'teaching',
                mean2: 'teaching',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가상',
                mean: 'email',
                mean2: 'email',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가설',
                mean: 'Hypothesis',
                mean2: 'Hypothesis',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '가세',
                mean: 'Gase',
                mean2: 'Gase',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '가속',
                mean: 'Acceleration',
                mean2: 'Acceleration',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '가열',
                mean: 'heating',
                mean2: 'heating',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '가책',
                mean: 'Bookstore',
                mean2: 'Bookstore',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '가출',
                mean: 'run away',
                mean2: 'run away',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '가혹00',
                mean: 'Hards 00',
                mean2: 'Hards 00',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '가훈',
                mean: 'Ga -hoon',
                mean2: 'Ga -hoon',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '각',
                mean: 'Each',
                mean2: 'Each',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '각계',
                mean: 'All walks of life',
                mean2: 'All walks of life',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '각계각층',
                mean: 'All walks of life',
                mean2: 'All walks of life',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '각도',
                mean: 'Angle',
                mean2: 'Angle',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '각본',
                mean: 'Script',
                mean2: 'Script',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '각성',
                mean: 'Awakening',
                mean2: 'Awakening',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '각양각색',
                mean: 'Various',
                mean2: 'Various',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '간담회',
                mean: 'Meeting',
                mean2: 'Meeting',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '간밤',
                mean: 'yesternight',
                mean2: 'yesternight',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '간부',
                mean: 'Cadre',
                mean2: 'Cadre',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '간주',
                mean: 'Residency',
                mean2: 'Residency',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '간첩',
                mean: 'Spy',
                mean2: 'Spy',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '갈래',
                mean: 'Shall we go',
                mean2: 'Shall we go',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '갈망',
                mean: 'craving',
                mean2: 'craving',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '갈피',
                mean: 'Galpi',
                mean2: 'Galpi',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '감',
                mean: 'Persimmon',
                mean2: 'Persimmon',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '감금',
                mean: 'Incarceration',
                mean2: 'Incarceration',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '감당',
                mean: 'Handling',
                mean2: 'Handling',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '감량',
                mean: 'outage',
                mean2: 'outage',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '감면',
                mean: 'Reduction',
                mean2: 'Reduction',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '감명',
                mean: 'Impression',
                mean2: 'Impression',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '감소세00',
                mean: 'Decrease 00',
                mean2: 'Decrease 00',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '감수',
                mean: 'Supervision',
                mean2: 'Supervision',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '감수성',
                mean: 'sensibility',
                mean2: 'sensibility',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '감안',
                mean: 'Consideration',
                mean2: 'Consideration',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '감언이설',
                mean: 'Tone',
                mean2: 'Tone',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '감원',
                mean: 'rundown',
                mean2: 'rundown',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '감지',
                mean: 'detect',
                mean2: 'detect',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '감촉',
                mean: 'Texture',
                mean2: 'Texture',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '감축',
                mean: 'Reduction',
                mean2: 'Reduction',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '감회',
                mean: 'Sentiment',
                mean2: 'Sentiment',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '값어치',
                mean: 'Value',
                mean2: 'Value',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '강간',
                mean: 'rape',
                mean2: 'rape',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '강세',
                mean: 'stress',
                mean2: 'stress',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '강압',
                mean: 'Coercion',
                mean2: 'Coercion',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '강점',
                mean: 'Strength',
                mean2: 'Strength',
                audio: '',
            },
        ],
        verb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가누다',
                mean: 'Go to',
                mean2: 'Go to',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가다듬다',
                mean: 'Trim',
                mean2: 'Trim',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가라앉히다',
                mean: 'Sink',
                mean2: 'Sink',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가려내다',
                mean: 'Hide',
                mean2: 'Hide',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가로지르다',
                mean: 'Cross',
                mean2: 'Cross',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가로채다',
                mean: 'Intercept',
                mean2: 'Intercept',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가하다',
                mean: 'Make',
                mean2: 'Make',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '간과하다',
                mean: 'Overlook',
                mean2: 'Overlook',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '감돌다',
                mean: 'Take',
                mean2: 'Take',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '감하다',
                mean: 'subtract',
                mean2: 'subtract',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '거듭나다',
                mean: 'Reborn',
                mean2: 'Reborn',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '거르다',
                mean: 'Filter',
                mean2: 'Filter',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '거르다',
                mean: 'Filter',
                mean2: 'Filter',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '거스르다',
                mean: 'Respect',
                mean2: 'Respect',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '거슬리다',
                mean: 'Bother',
                mean2: 'Bother',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '걷잡다',
                mean: 'Take away',
                mean2: 'Take away',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '걸려들다',
                mean: 'Hang',
                mean2: 'Hang',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '걸터앉다',
                mean: 'Go down',
                mean2: 'Go down',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '게을리하다',
                mean: 'Neglect',
                mean2: 'Neglect',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '겨누다',
                mean: 'aim',
                mean2: 'aim',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '겨루다',
                mean: 'cope',
                mean2: 'cope',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '견주다',
                mean: 'compare with',
                mean2: 'compare with',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '결정짓다',
                mean: 'Decide',
                mean2: 'Decide',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '곁들이다',
                mean: 'Be served',
                mean2: 'Be served',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '고다',
                mean: 'Go',
                mean2: 'Go',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '고사하다00',
                mean: 'Death 00',
                mean2: 'Death 00',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '곤두세우다',
                mean: 'Ripple',
                mean2: 'Ripple',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '곪다',
                mean: 'fester',
                mean2: 'fester',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '구기다',
                mean: 'crumple',
                mean2: 'crumple',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '굴다',
                mean: 'behave',
                mean2: 'behave',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '굴리다',
                mean: 'tumble',
                mean2: 'tumble',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '굶주리다',
                mean: 'Hungry',
                mean2: 'Hungry',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '그릇되다',
                mean: 'Behalf',
                mean2: 'Behalf',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '기리다',
                mean: 'commend',
                mean2: 'commend',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '기어가다',
                mean: 'Crawl',
                mean2: 'Crawl',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '기어들다',
                mean: 'Crawl',
                mean2: 'Crawl',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '기어오르다',
                mean: 'Climb',
                mean2: 'Climb',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '기웃거리다',
                mean: 'Snoop',
                mean2: 'Snoop',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '기인하다',
                mean: 'Rig',
                mean2: 'Rig',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '길들이다',
                mean: 'Tame',
                mean2: 'Tame',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '깃들다',
                mean: 'Fidle',
                mean2: 'Fidle',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '까무러치다',
                mean: 'Crush',
                mean2: 'Crush',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '깨우치다',
                mean: 'Enlighten',
                mean2: 'Enlighten',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '꺼리다',
                mean: 'scruple',
                mean2: 'scruple',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '껴입다',
                mean: 'Wear',
                mean2: 'Wear',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '꼬이다',
                mean: 'Twist',
                mean2: 'Twist',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '꼬집다',
                mean: 'make cynical',
                mean2: 'make cynical',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '꾀하다',
                mean: 'plot',
                mean2: 'plot',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '꿈틀거리다',
                mean: 'Wriggle',
                mean2: 'Wriggle',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '꿰다',
                mean: 'pass through',
                mean2: 'pass through',
                audio: '',
            },
        ],
        adjective:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가냘프다',
                mean: 'Thin',
                mean2: 'Thin',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가쁘다',
                mean: 'Be short',
                mean2: 'Be short',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가엾다',
                mean: 'Poverty',
                mean2: 'Poverty',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가파르다',
                mean: 'Steep',
                mean2: 'Steep',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '각박하다',
                mean: 'Bite',
                mean2: 'Bite',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '각별하다',
                mean: 'Exempt',
                mean2: 'Exempt',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '간략하다',
                mean: 'Briefly',
                mean2: 'Briefly',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '감격스럽다',
                mean: 'Emotional',
                mean2: 'Emotional',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '강인하다',
                mean: 'Be strong',
                mean2: 'Be strong',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '강직하다',
                mean: 'Rigor',
                mean2: 'Rigor',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '개운하다',
                mean: 'Refresh',
                mean2: 'Refresh',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '거뜬하다',
                mean: 'Rug',
                mean2: 'Rug',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '거룩하다',
                mean: 'Holy',
                mean2: 'Holy',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '거북하다',
                mean: 'Get stuck',
                mean2: 'Get stuck',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '거창하다',
                mean: 'Tremend',
                mean2: 'Tremend',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '건방지다',
                mean: 'be impertinent',
                mean2: 'be impertinent',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '건장하다',
                mean: 'Sturgy',
                mean2: 'Sturgy',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '걸맞다',
                mean: 'match',
                mean2: 'match',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '견고하다',
                mean: 'Be firm',
                mean2: 'Be firm',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '경건하다',
                mean: 'Be godly',
                mean2: 'Be godly',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '경이롭다',
                mean: 'Wonderful',
                mean2: 'Wonderful',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '고귀하다',
                mean: 'Noble',
                mean2: 'Noble',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '고달프다',
                mean: 'Pour',
                mean2: 'Pour',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '고되다',
                mean: 'Be in trouble',
                mean2: 'Be in trouble',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '고약하다',
                mean: 'Nasty',
                mean2: 'Nasty',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '공공연하다',
                mean: 'Open',
                mean2: 'Open',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '공허하다',
                mean: 'Empty',
                mean2: 'Empty',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '과격하다',
                mean: 'Be radical',
                mean2: 'Be radical',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '광범위하다',
                mean: 'Ripple',
                mean2: 'Ripple',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '광활하다',
                mean: 'Vast',
                mean2: 'Vast',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '교묘하다',
                mean: 'Cylind',
                mean2: 'Cylind',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '교활하다',
                mean: 'Cunning',
                mean2: 'Cunning',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '구태의연하다',
                mean: 'Tender',
                mean2: 'Tender',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '궂다',
                mean: 'Be bad',
                mean2: 'Be bad',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '그윽하다',
                mean: 'Be able to',
                mean2: 'Be able to',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '그지없다',
                mean: 'No way',
                mean2: 'No way',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '급급하다',
                mean: 'Be in urgent',
                mean2: 'Be in urgent',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '기묘하다',
                mean: 'Bizarre',
                mean2: 'Bizarre',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '기이하다',
                mean: 'Bizarre',
                mean2: 'Bizarre',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '기특하다',
                mean: 'Unusual',
                mean2: 'Unusual',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '긴밀하다',
                mean: 'Close',
                mean2: 'Close',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '길쭉하다',
                mean: 'Be elongated',
                mean2: 'Be elongated',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '까마득하다',
                mean: 'Crush',
                mean2: 'Crush',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '꺼림칙하다',
                mean: 'Be reluctant',
                mean2: 'Be reluctant',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '끈끈하다',
                mean: 'Stick',
                mean2: 'Stick',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '끈질기다',
                mean: 'Persistent',
                mean2: 'Persistent',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '나른하다',
                mean: 'Drowse',
                mean2: 'Drowse',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '나약하다',
                mean: 'Weaken',
                mean2: 'Weaken',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '나지막하다',
                mean: 'Be',
                mean2: 'Be',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '난감하다',
                mean: 'Be in trouble',
                mean2: 'Be in trouble',
                audio: '',
            },
        ],
        adverb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가까스로',
                mean: 'barely',
                mean2: 'barely',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가뜩이나',
                mean: 'Tightly',
                mean2: 'Tightly',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가령',
                mean: 'chamberlain',
                mean2: 'chamberlain',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가히',
                mean: 'Well',
                mean2: 'Well',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '각별히',
                mean: 'Extravagantly',
                mean2: 'Extravagantly',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '감쪽같이',
                mean: 'Like',
                mean2: 'Like',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '갓',
                mean: 'God',
                mean2: 'God',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '거듭',
                mean: 'Repeatedly',
                mean2: 'Repeatedly',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '거침없이',
                mean: 'Unobtrusive',
                mean2: 'Unobtrusive',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '걸핏하면',
                mean: 'Fit',
                mean2: 'Fit',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '고루',
                mean: 'Even',
                mean2: 'Even',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '고스란히',
                mean: 'bag and baggage',
                mean2: 'bag and baggage',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '고요히',
                mean: 'calmly',
                mean2: 'calmly',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '곰곰이',
                mean: 'Well',
                mean2: 'Well',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '공연히',
                mean: 'vainly',
                mean2: 'vainly',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '과감히',
                mean: 'Boldly',
                mean2: 'Boldly',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '구태여',
                mean: 'Old',
                mean2: 'Old',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '그나저나',
                mean: 'by the way',
                mean2: 'by the way',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '급기야',
                mean: 'Suddenly',
                mean2: 'Suddenly',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '기꺼이',
                mean: 'Gladly',
                mean2: 'Gladly',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '기껏',
                mean: 'at the outside',
                mean2: 'at the outside',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '기어이',
                mean: 'Gear',
                mean2: 'Gear',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '기어코',
                mean: 'Gearco',
                mean2: 'Gearco',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '기필코',
                mean: 'Ki Pilko',
                mean2: 'Ki Pilko',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '깊숙이',
                mean: 'Deeply',
                mean2: 'Deeply',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '꼬치꼬치',
                mean: 'Skewer',
                mean2: 'Skewer',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '꾹',
                mean: '꾹',
                mean2: '꾹',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '끔찍이',
                mean: 'dearly',
                mean2: 'dearly',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '난데없이',
                mean: 'Nowadays',
                mean2: 'Nowadays',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '난생',
                mean: 'Ovation',
                mean2: 'Ovation',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '남김없이',
                mean: 'Unlawful',
                mean2: 'Unlawful',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '낱낱이',
                mean: 'particularly',
                mean2: 'particularly',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '내지',
                mean: 'Or',
                mean2: 'Or',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '느닷없이',
                mean: 'In a hurry',
                mean2: 'In a hurry',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '다분히',
                mean: 'Dull',
                mean2: 'Dull',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '다시금',
                mean: 'Again',
                mean2: 'Again',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '다짜고짜',
                mean: 'suddenly',
                mean2: 'suddenly',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '단단히',
                mean: 'firmly',
                mean2: 'firmly',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '단번에',
                mean: 'At once',
                mean2: 'At once',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '단숨에',
                mean: 'at a whack',
                mean2: 'at a whack',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '단연',
                mean: 'far and away',
                mean2: 'far and away',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '당당히',
                mean: 'Proudly',
                mean2: 'Proudly',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '대뜸',
                mean: 'Moxibustion',
                mean2: 'Moxibustion',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '더군다나',
                mean: 'Furthermore',
                mean2: 'Furthermore',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '더더욱',
                mean: 'Even more',
                mean2: 'Even more',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '더러00',
                mean: 'Some 00',
                mean2: 'Some 00',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '덜컥',
                mean: 'Run',
                mean2: 'Run',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '두루',
                mean: 'All -round',
                mean2: 'All -round',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '둥둥',
                mean: 'Dung',
                mean2: 'Dung',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '딱히',
                mean: 'Just',
                mean2: 'Just',
                audio: '',
            },
        ],
    }
];