//5급
export const data5 = [
    {
        noun : [
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가게',
                mean: '가게',
                mean2: '가게',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가곡',
                mean: '가곡을 듣다 ',
                mean2: '가곡을 듣다 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가공',
                mean: '가공',
                mean2: '가공',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가구',
                mean: '가구',
                mean2: '가구',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가닥',
                mean: '가닥을 잡다 ',
                mean2: '가닥을 잡다 ',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가로수',
                mean: '가로수를 심다 ',
                mean2: '가로수를 심다 ',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가면',
                mean: '가면을 쓰다 ',
                mean2: '가면을 쓰다 ',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '가문',
                mean: '가문의 영광',
                mean2: '가문의 영광',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '가사',
                mean: '가사',
                mean2: '가사',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '가속화',
                mean: '성장 과속화 ',
                mean2: '성장 과속화 ',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '가시',
                mean: '가시',
                mean2: '가시',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '가야금',
                mean: '가야금을 연주하다',
                mean2: '가야금을 연주하다',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '가옥',
                mean: '전통 가옥',
                mean2: '전통 가옥',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '가요계',
                mean: '가요계에 종사하다',
                mean2: '가요계에 종사하다',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '가장자리',
                mean: '가장자리에 놓다 ',
                mean2: '가장자리에 놓다 ',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '가중',
                mean: '책임 가중',
                mean2: '책임 가중',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '가창력',
                mean: '가창력이 뛰어나다 ',
                mean2: '가창력이 뛰어나다 ',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '가축',
                mean: '가축을 기르다 ',
                mean2: '가축을 기르다 ',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '가해자',
                mean: '가해자를 처벌하다',
                mean2: '가해자를 처벌하다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '각광',
                mean: '각광을 받다 ',
                mean2: '각광을 받다 ',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '각지',
                mean: '각지를 여행하다',
                mean2: '각지를 여행하다',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '간접',
                mean: '간접 광고 ',
                mean2: '간접 광고 ',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '간직00',
                mean: '사진을 간직하다',
                mean2: '사진을 간직하다',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '갈대',
                mean: '갈대처럼 흔들리다 ',
                mean2: '갈대처럼 흔들리다 ',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '감격',
                mean: '감격의 눈물',
                mean2: '감격의 눈물',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '감사',
                mean: '감사',
                mean2: '감사',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '감상',
                mean: '감상',
                mean2: '감상',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '감성',
                mean: '감성이 풍부하다 ',
                mean2: '감성이 풍부하다 ',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '감염',
                mean: '세균 감염',
                mean2: '세균 감염',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '감탄',
                mean: '감탄이 나오다 ',
                mean2: '감탄이 나오다 ',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '감탄사',
                mean: '감탄사가 나오다 ',
                mean2: '감탄사가 나오다 ',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '갑',
                mean: '둑을 쌓다',
                mean2: '둑을 쌓다',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '강국',
                mean: '스포츠 강국',
                mean2: '스포츠 강국',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '강당',
                mean: '강당에 모이다 ',
                mean2: '강당에 모이다 ',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '강대국',
                mean: '강대국으로 발전하다 ',
                mean2: '강대국으로 발전하다 ',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '강도',
                mean: '강도',
                mean2: '강도',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '강력00',
                mean: '강력 대처',
                mean2: '강력 대처',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '강산',
                mean: '강산',
                mean2: '강산',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '강연',
                mean: '강연을 하다 ',
                mean2: '강연을 하다 ',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '강우량',
                mean: '강우량이 많다 ',
                mean2: '강우량이 많다 ',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '강자',
                mean: '강자를 물리치다',
                mean2: '강자를 물리치다',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '강좌',
                mean: '강좌를 개설하다',
                mean2: '강좌를 개설하다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '강풍',
                mean: '강풍이 불다 ',
                mean2: '강풍이 불다 ',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '강화',
                mean: '국력 강화',
                mean2: '국력 강화',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '개강',
                mean: '개강 파티',
                mean2: '개강 파티',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '개개인',
                mean: '개개인의 능력 ',
                mean2: '개개인의 능력 ',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '개막식',
                mean: '월드컵 개막식',
                mean2: '월드컵 개막식',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '개봉',
                mean: '편지 개봉',
                mean2: '편지 개봉',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '개설',
                mean: '강좌 개설',
                mean2: '강좌 개설',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '개수',
                mean: '개수를 세다 ',
                mean2: '개수를 세다 ',
                audio: '',
            },
        ],
        verb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가리다',
                mean: '가리다',
                mean2: '가리다',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가시다',
                mean: '피로가 가시다',
                mean2: '피로가 가시다',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '갈다',
                mean: '갈다',
                mean2: '갈다',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '감기다',
                mean: '감기다',
                mean2: '감기다',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '거느리다',
                mean: '백성을 거느리다 ',
                mean2: '백성을 거느리다 ',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '거닐다',
                mean: '거리를 거닐다 ',
                mean2: '거리를 거닐다 ',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '걷어차다',
                mean: '발로 걷어차다',
                mean2: '발로 걷어차다',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '겁내다',
                mean: '죽음을 겁내다',
                mean2: '죽음을 겁내다',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '겸하다',
                mean: '두 직업을 겸하다',
                mean2: '두 직업을 겸하다',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '고이다',
                mean: '물이 고이다',
                mean2: '물이 고이다',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '관련짓다',
                mean: '관련지어 말하다 ',
                mean2: '관련지어 말하다 ',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '관하다',
                mean: '사랑에 관한 글',
                mean2: '사랑에 관한 글',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '구겨지다',
                mean: '옷이 구겨지다',
                mean2: '옷이 구겨지다',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '구르다',
                mean: '구르다',
                mean2: '구르다',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '굳히다',
                mean: '시멘트를 굳히다',
                mean2: '시멘트를 굳히다',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '굴러가다',
                mean: '바퀴가 굴러가다',
                mean2: '바퀴가 굴러가다',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '그리다',
                mean: '그리다',
                mean2: '그리다',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '기하다',
                mean: '신중을 기하다',
                mean2: '신중을 기하다',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '깜짝하다',
                mean: '깜짝하다',
                mean2: '깜짝하다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '꺼지다',
                mean: '꺼지다',
                mean2: '꺼지다',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '꺾이다',
                mean: '나뭇가지가 꺾이다 ',
                mean2: '나뭇가지가 꺾이다 ',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '꼬다',
                mean: '다리를 꼬다',
                mean2: '다리를 꼬다',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '꾸짖다',
                mean: '잘못을 꾸짖다',
                mean2: '잘못을 꾸짖다',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '꿰매다',
                mean: '옷을 꿰매다',
                mean2: '옷을 꿰매다',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '끄집어내다',
                mean: '구석에서 끄집어내다',
                mean2: '구석에서 끄집어내다',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '끊이다',
                mean: '손님이 끈이지 않다',
                mean2: '손님이 끈이지 않다',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '끌어내다',
                mean: '밖으로 끌어내다',
                mean2: '밖으로 끌어내다',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '끌어들이다',
                mean: '안으로 끌어들이다',
                mean2: '안으로 끌어들이다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '끌어올리다',
                mean: '수준을 끌어올리다',
                mean2: '수준을 끌어올리다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '끝맺다',
                mean: '일을 끝맺다',
                mean2: '일을 끝맺다',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '나돌다',
                mean: '밖으로 나돌다',
                mean2: '밖으로 나돌다',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '낚다',
                mean: '물고기를 낚다 ',
                mean2: '물고기를 낚다 ',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '날아들다',
                mean: '새가 날아들다',
                mean2: '새가 날아들다',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '날아오르다',
                mean: '새가 날아오르다',
                mean2: '새가 날아오르다',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '내딛다',
                mean: '걸음을 내딛다',
                mean2: '걸음을 내딛다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '내리치다',
                mean: '뒤통수를 내리치다',
                mean2: '뒤통수를 내리치다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '내뱉다',
                mean: '한숨을 내뱉다 ',
                mean2: '한숨을 내뱉다 ',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '내보이다',
                mean: '내보이다',
                mean2: '내보이다',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '내비치다',
                mean: '햇살이 내비치다',
                mean2: '햇살이 내비치다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '내쉬다',
                mean: '한숨을 내쉬다',
                mean2: '한숨을 내쉬다',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '내오다',
                mean: '물건을 내오다 ',
                mean2: '물건을 내오다 ',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '내지르다',
                mean: '소리를 내지르다',
                mean2: '소리를 내지르다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '놓아주다',
                mean: '물고기를 놓아주다 ',
                mean2: '물고기를 놓아주다 ',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '누다',
                mean: '오줌을 누다',
                mean2: '오줌을 누다',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '누리다',
                mean: '누리다',
                mean2: '누리다',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '눈치채다',
                mean: '눈치채다',
                mean2: '눈치채다',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '눌리다',
                mean: '눌리다',
                mean2: '눌리다',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '뉘우치다',
                mean: '잘못을 뉘우치다',
                mean2: '잘못을 뉘우치다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '늘어지다',
                mean: '피부가 늘어지다 ',
                mean2: '피부가 늘어지다 ',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '다다르다',
                mean: '정상에 다다르다',
                mean2: '정상에 다다르다',
                audio: '',
            },
        ],
        adjective:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가느다랗다',
                mean: '손가락이 가느다랗다',
                mean2: '손가락이 가느다랗다',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '간결하다',
                mean: '디자인이 간결하다 ',
                mean2: '디자인이 간결하다 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '간소하다',
                mean: '옷차림이 간소하다',
                mean2: '옷차림이 간소하다',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '감미롭다',
                mean: '음악이 감미롭다 ',
                mean2: '음악이 감미롭다 ',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '갑갑하다',
                mean: '마음이 갑갑하다 ',
                mean2: '마음이 갑갑하다 ',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '값지다',
                mean: '값진 보석',
                mean2: '값진 보석',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '강렬하다',
                mean: '빛이 강렬하다 ',
                mean2: '빛이 강렬하다 ',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '거세다',
                mean: '바람이 거세다 ',
                mean2: '바람이 거세다 ',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '격렬하다',
                mean: '싸움이 격렬하다 ',
                mean2: '싸움이 격렬하다 ',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '경솔하다',
                mean: '경솔한 말',
                mean2: '경솔한 말',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '경쾌하다',
                mean: '기분이 경쾌하다',
                mean2: '기분이 경쾌하다',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '고단하다',
                mean: '몸이 고단하다',
                mean2: '몸이 고단하다',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '고르다',
                mean: '고르다',
                mean2: '고르다',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '고상하다',
                mean: '말투가 고상하다',
                mean2: '말투가 고상하다',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '고생스럽다',
                mean: '생활이 고생스럽다',
                mean2: '생활이 고생스럽다',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '공평하다',
                mean: '공평한 세상',
                mean2: '공평한 세상',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '과감하다',
                mean: '과감한 행동',
                mean2: '과감한 행동',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '과도하다',
                mean: '과도한 경쟁',
                mean2: '과도한 경쟁',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '과하다',
                mean: '과하다',
                mean2: '과하다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '관대하다',
                mean: '관대하다',
                mean2: '관대하다',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '극심하다',
                mean: '피해가 극심하다',
                mean2: '피해가 극심하다',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '근사하다',
                mean: '옷차림이 근사하다',
                mean2: '옷차림이 근사하다',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '급격하다',
                mean: '변화가 급격하다',
                mean2: '변화가 급격하다',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '기름지다',
                mean: '음식이 기름지다',
                mean2: '음식이 기름지다',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '기막히다',
                mean: '경치가 기막히다',
                mean2: '경치가 기막히다',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '기발하다',
                mean: '생각이 기발하다',
                mean2: '생각이 기발하다',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '끔찍하다',
                mean: '끔찍한 사건 ',
                mean2: '끔찍한 사건 ',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '남다르다',
                mean: '재능이 남다르다',
                mean2: '재능이 남다르다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '납작하다',
                mean: '코가 납작하다',
                mean2: '코가 납작하다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '낯익다',
                mean: '얼굴이 낯익다 ',
                mean2: '얼굴이 낯익다 ',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '네모나다',
                mean: '얼굴이 네모나다 ',
                mean2: '얼굴이 네모나다 ',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '누렇다',
                mean: '이가 누렇다 ',
                mean2: '이가 누렇다 ',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '능숙하다',
                mean: '솜씨가 능숙하다',
                mean2: '솜씨가 능숙하다',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '다급하다',
                mean: '상황이 다급하다',
                mean2: '상황이 다급하다',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '단조롭다',
                mean: '생활이 단조롭다 ',
                mean2: '생활이 단조롭다 ',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '대견하다',
                mean: '자식이 대견하다',
                mean2: '자식이 대견하다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '덜하다',
                mean: '고생이 덜하다',
                mean2: '고생이 덜하다',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '두텁다',
                mean: '친분이 두텁다',
                mean2: '친분이 두텁다',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '둔하다',
                mean: '머리가 둔하다',
                mean2: '머리가 둔하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '따갑다',
                mean: '따가운 햇볕',
                mean2: '따가운 햇볕',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '떫다',
                mean: '감이 떫다',
                mean2: '감이 떫다',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '떳떳하다',
                mean: '행동이 떳떳하다',
                mean2: '행동이 떳떳하다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '또렷하다',
                mean: '기억이 또렷하다',
                mean2: '기억이 또렷하다',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '뜸하다',
                mean: '소식이 뜸하다',
                mean2: '소식이 뜸하다',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '막막하다',
                mean: '막막하다',
                mean2: '막막하다',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '매끄럽다',
                mean: '피부가 매끄럽다',
                mean2: '피부가 매끄럽다',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '매섭다',
                mean: '눈초리가 매섭다',
                mean2: '눈초리가 매섭다',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '매콤하다',
                mean: '맛이 매콤하다',
                mean2: '맛이 매콤하다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '머지않다',
                mean: '승리가 머지 않다',
                mean2: '승리가 머지 않다',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '먹음직스럽다',
                mean: '음식이 먹음직스럽다',
                mean2: '음식이 먹음직스럽다',
                audio: '',
            },
        ],
        adverb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가지런히',
                mean: '가지런히 꽂다 ',
                mean2: '가지런히 꽂다 ',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '간간이',
                mean: '간간이 나타나다',
                mean2: '간간이 나타나다',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '간절히',
                mean: '간절히 바라다 ',
                mean2: '간절히 바라다 ',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '강력히',
                mean: '강력히 주장하다 ',
                mean2: '강력히 주장하다 ',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '그리',
                mean: '그리',
                mean2: '그리',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '그리하여',
                mean: '그리하여',
                mean2: '그리하여',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '금세',
                mean: '금세 잠들다',
                mean2: '금세 잠들다',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '까딱',
                mean: '까딱 움직이다',
                mean2: '까딱 움직이다',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '깡충깡충',
                mean: '깡충깡충 뛰다 ',
                mean2: '깡충깡충 뛰다 ',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '꼬르륵',
                mean: '꼬르륵 소리가 나다',
                mean2: '꼬르륵 소리가 나다',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '꼬박',
                mean: '꼬박',
                mean2: '꼬박',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '꼬박꼬박',
                mean: '돈을 꼬박꼬박 내다',
                mean2: '돈을 꼬박꼬박 내다',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '꼭꼭',
                mean: '꼭꼭',
                mean2: '꼭꼭',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '꼼짝없이',
                mean: '꼼짝없이 당하다 ',
                mean2: '꼼짝없이 당하다 ',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '꽁꽁',
                mean: '꽁꽁 얼다',
                mean2: '꽁꽁 얼다',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '꾸벅꾸벅',
                mean: '꾸벅꾸벅',
                mean2: '꾸벅꾸벅',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '나날이',
                mean: '나날이 늘다 ',
                mean2: '나날이 늘다 ',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '날로',
                mean: '날로',
                mean2: '날로',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '남몰래',
                mean: '남몰래 돕다',
                mean2: '남몰래 돕다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '다름없이',
                mean: '평소와 다름없이',
                mean2: '평소와 다름없이',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '단',
                mean: '단',
                mean2: '단',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '대대로',
                mean: '자손 대대로',
                mean2: '자손 대대로',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '더없이',
                mean: '더없이 만족하다',
                mean2: '더없이 만족하다',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '동동',
                mean: '동동',
                mean2: '동동',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '듬뿍',
                mean: '듬뿍 담다 ',
                mean2: '듬뿍 담다 ',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '딱',
                mean: '딱',
                mean2: '딱',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '떡',
                mean: '떡',
                mean2: '떡',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '똑00',
                mean: '똑 닮다',
                mean2: '똑 닮다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '똑똑',
                mean: '똑똑 두드리다',
                mean2: '똑똑 두드리다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '뚜렷이',
                mean: '뚜렷이 구별되다',
                mean2: '뚜렷이 구별되다',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '뚝',
                mean: '뚝',
                mean2: '뚝',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '뚝뚝',
                mean: '뚝뚝',
                mean2: '뚝뚝',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '마저',
                mean: '마저 먹다',
                mean2: '마저 먹다',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '멍하니',
                mean: '멍하니 바라보다 ',
                mean2: '멍하니 바라보다 ',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '명백히',
                mean: '명백히 밝히다',
                mean2: '명백히 밝히다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '명확히',
                mean: '명확히 밝히다',
                mean2: '명확히 밝히다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '모조리',
                mean: '모조리 사라지다',
                mean2: '모조리 사라지다',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '무심코',
                mean: '무심코 지나치다',
                mean2: '무심코 지나치다',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '밤낮없이',
                mean: '밤낮없이 일하다',
                mean2: '밤낮없이 일하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '버럭',
                mean: '버럭 화를 내다',
                mean2: '버럭 화를 내다',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '번번이',
                mean: '번번이 실수하다',
                mean2: '번번이 실수하다',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '변함없이',
                mean: '변함없이 같다',
                mean2: '변함없이 같다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '보글보글',
                mean: '보글보글 끓다',
                mean2: '보글보글 끓다',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '부쩍',
                mean: '부쩍 늘다',
                mean2: '부쩍 늘다',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '불행히',
                mean: '불행히 살다',
                mean2: '불행히 살다',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '뻘뻘',
                mean: '뻘뻘',
                mean2: '뻘뻘',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '살금살금',
                mean: '살금살금 다가가다',
                mean2: '살금살금 다가가다',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '살며시',
                mean: '살며시 웃다',
                mean2: '살며시 웃다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '설사',
                mean: '설사',
                mean2: '설사',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '성실히',
                mean: '성실히 일하다',
                mean2: '성실히 일하다',
                audio: '',
            },
        ],
    }
];

//6급
export const data6 = [
    {
        noun : [
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가계',
                mean: '가계',
                mean2: '가계',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가늠',
                mean: '가늠이 안 되다 ',
                mean2: '가늠이 안 되다 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가담',
                mean: '시위 가담',
                mean2: '시위 가담',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가동',
                mean: '기계 가동',
                mean2: '기계 가동',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가르침',
                mean: '가르침을 받다 ',
                mean2: '가르침을 받다 ',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가상',
                mean: '가상의 공간',
                mean2: '가상의 공간',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가설',
                mean: '가설',
                mean2: '가설',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '가세',
                mean: '가세',
                mean2: '가세',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '가속',
                mean: '가속이 붙다 ',
                mean2: '가속이 붙다 ',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '가열',
                mean: '급속 가열',
                mean2: '급속 가열',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '가책',
                mean: '양심의 가책',
                mean2: '양심의 가책',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '가출',
                mean: '가출 청소년',
                mean2: '가출 청소년',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '가혹00',
                mean: '가혹 행위',
                mean2: '가혹 행위',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '가훈',
                mean: '가훈을 정하다',
                mean2: '가훈을 정하다',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '각',
                mean: '각',
                mean2: '각',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '각계',
                mean: '각계 대표 ',
                mean2: '각계 대표 ',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '각계각층',
                mean: '사회 각계각층',
                mean2: '사회 각계각층',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '각도',
                mean: '각도를 재다 ',
                mean2: '각도를 재다 ',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '각본',
                mean: '각본을 쓰다 ',
                mean2: '각본을 쓰다 ',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '각성',
                mean: '각성을 촉구하다',
                mean2: '각성을 촉구하다',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '각양각색',
                mean: '0',
                mean2: '0',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '간담회',
                mean: '간담회에 참여하다 ',
                mean2: '간담회에 참여하다 ',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '간밤',
                mean: '간밤에 꿈을 꾸다 ',
                mean2: '간밤에 꿈을 꾸다 ',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '간부',
                mean: '회사 간부',
                mean2: '회사 간부',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '간주',
                mean: '간주',
                mean2: '간주',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '간첩',
                mean: '간첩을 잡다 ',
                mean2: '간첩을 잡다 ',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '갈래',
                mean: '하위 갈래',
                mean2: '하위 갈래',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '갈망',
                mean: '자유를 갈망하다',
                mean2: '자유를 갈망하다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '갈피',
                mean: '갈피를 잡다 ',
                mean2: '갈피를 잡다 ',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '감',
                mean: '감',
                mean2: '감',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '감금',
                mean: '감금을 당하다',
                mean2: '감금을 당하다',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '감당',
                mean: '비용 감당',
                mean2: '비용 감당',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '감량',
                mean: '체중 감량',
                mean2: '체중 감량',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '감면',
                mean: '학비 감면',
                mean2: '학비 감면',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '감명',
                mean: '감명을 받다',
                mean2: '감명을 받다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '감소세00',
                mean: '감소세를 보이다 ',
                mean2: '감소세를 보이다 ',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '감수',
                mean: '감수',
                mean2: '감수',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '감수성',
                mean: '감수성이 풍부하다 ',
                mean2: '감수성이 풍부하다 ',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '감안',
                mean: '현실을 감안하다',
                mean2: '현실을 감안하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '감언이설',
                mean: '0',
                mean2: '0',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '감원',
                mean: '근로자 감원',
                mean2: '근로자 감원',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '감지',
                mean: '감지 능력',
                mean2: '감지 능력',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '감촉',
                mean: '감촉이 부드럽다 ',
                mean2: '감촉이 부드럽다 ',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '감축',
                mean: '예산 감축',
                mean2: '예산 감축',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '감회',
                mean: '감회가 새롭다 ',
                mean2: '감회가 새롭다 ',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '값어치',
                mean: '값어치가 떨어지다 ',
                mean2: '값어치가 떨어지다 ',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '강간',
                mean: '강간을 당하다 ',
                mean2: '강간을 당하다 ',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '강세',
                mean: '강세를 보이다 ',
                mean2: '강세를 보이다 ',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '강압',
                mean: '강압을 받다 ',
                mean2: '강압을 받다 ',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '강점',
                mean: '개수를 세다 ',
                mean2: '개수를 세다 ',
                audio: '',
            },
        ],
        verb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가누다',
                mean: '몸을 가누다 ',
                mean2: '몸을 가누다 ',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가다듬다',
                mean: '마음을 가다듬다 ',
                mean2: '마음을 가다듬다 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가라앉히다',
                mean: '찌꺼기를 가라앉히다 ',
                mean2: '찌꺼기를 가라앉히다 ',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가려내다',
                mean: '불량품을 가려내다',
                mean2: '불량품을 가려내다',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '가로지르다',
                mean: '도로를 가로지르다 ',
                mean2: '도로를 가로지르다 ',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '가로채다',
                mean: '돈을 가로채다 ',
                mean2: '돈을 가로채다 ',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '가하다',
                mean: '가하다',
                mean2: '가하다',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '간과하다',
                mean: '문제를 간과하다',
                mean2: '문제를 간과하다',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '감돌다',
                mean: '긴장이 감돌다 ',
                mean2: '긴장이 감돌다 ',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '감하다',
                mean: '월급을 감하다 ',
                mean2: '월급을 감하다 ',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '거듭나다',
                mean: '새사람으로 거듭나다',
                mean2: '새사람으로 거듭나다',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '거르다',
                mean: '거르다',
                mean2: '거르다',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '거르다',
                mean: '거르다',
                mean2: '거르다',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '거스르다',
                mean: '거스르다',
                mean2: '거스르다',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '거슬리다',
                mean: '눈에 거슬리다',
                mean2: '눈에 거슬리다',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '걷잡다',
                mean: '걷잡을 수 없다',
                mean2: '걷잡을 수 없다',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '걸려들다',
                mean: '덫에 걸려들다 ',
                mean2: '덫에 걸려들다 ',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '걸터앉다',
                mean: '의자에 걸터앉다',
                mean2: '의자에 걸터앉다',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '게을리하다',
                mean: '일을 게을리하다',
                mean2: '일을 게을리하다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '겨누다',
                mean: '총을 겨누다 ',
                mean2: '총을 겨누다 ',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '겨루다',
                mean: '승부를 겨루다 ',
                mean2: '승부를 겨루다 ',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '견주다',
                mean: '실력을 견주다 ',
                mean2: '실력을 견주다 ',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '결정짓다',
                mean: '승패를 결정짓다',
                mean2: '승패를 결정짓다',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '곁들이다',
                mean: '양념을 곁들이다',
                mean2: '양념을 곁들이다',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '고다',
                mean: '사골을 고다',
                mean2: '사골을 고다',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '고사하다00',
                mean: '1등은 고사하고',
                mean2: '1등은 고사하고',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '곤두세우다',
                mean: '신경을 곤두세우다 ',
                mean2: '신경을 곤두세우다 ',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '곪다',
                mean: '상처가 곪다',
                mean2: '상처가 곪다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '구기다',
                mean: '종이를 구기다',
                mean2: '종이를 구기다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '굴다',
                mean: '귀찮게 굴다',
                mean2: '귀찮게 굴다',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '굴리다',
                mean: '공을 굴리다',
                mean2: '공을 굴리다',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '굶주리다',
                mean: '굶주린 배',
                mean2: '굶주린 배',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '그릇되다',
                mean: '그릇된 가치관',
                mean2: '그릇된 가치관',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '기리다',
                mean: '고인을 기리다',
                mean2: '고인을 기리다',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '기어가다',
                mean: '바닥을 기어가다',
                mean2: '바닥을 기어가다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '기어들다',
                mean: '동굴로 기어들다',
                mean2: '동굴로 기어들다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '기어오르다',
                mean: '나무에 기어오르다',
                mean2: '나무에 기어오르다',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '기웃거리다',
                mean: '방 안을 기웃거리다',
                mean2: '방 안을 기웃거리다',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '기인하다',
                mean: '부주의에 기인하다',
                mean2: '부주의에 기인하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '길들이다',
                mean: '강아지를 길들이다',
                mean2: '강아지를 길들이다',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '깃들다',
                mean: '영혼이 깃들다',
                mean2: '영혼이 깃들다',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '까무러치다',
                mean: '놀라서 까무러치다',
                mean2: '놀라서 까무러치다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '깨우치다',
                mean: '원리를 깨우치다',
                mean2: '원리를 깨우치다',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '꺼리다',
                mean: '공개를 꺼리다',
                mean2: '공개를 꺼리다',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '껴입다',
                mean: '옷을 껴입다',
                mean2: '옷을 껴입다',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '꼬이다',
                mean: '꼬이다',
                mean2: '꼬이다',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '꼬집다',
                mean: '볼을 꼬집다',
                mean2: '볼을 꼬집다',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '꾀하다',
                mean: '변화를 꾀하다',
                mean2: '변화를 꾀하다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '꿈틀거리다',
                mean: '지렁이가 꿈틀거리다',
                mean2: '지렁이가 꿈틀거리다',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '꿰다',
                mean: '정상에 다다르다',
                mean2: '정상에 다다르다',
                audio: '',
            },
        ],
        adjective:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가냘프다',
                mean: '몸이 가냘프다 ',
                mean2: '몸이 가냘프다 ',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가쁘다',
                mean: '숨이 가쁘다 ',
                mean2: '숨이 가쁘다 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가엾다',
                mean: '아이가 가엾다 ',
                mean2: '아이가 가엾다 ',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가파르다',
                mean: '언덕이 가파르다 ',
                mean2: '언덕이 가파르다 ',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '각박하다',
                mean: '세상이 각박하다',
                mean2: '세상이 각박하다',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '각별하다',
                mean: '마음이 각별하다',
                mean2: '마음이 각별하다',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '간략하다',
                mean: '설명이 간략하다 ',
                mean2: '설명이 간략하다 ',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '감격스럽다',
                mean: '감격스러운 순간',
                mean2: '감격스러운 순간',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '강인하다',
                mean: '강인한 체력',
                mean2: '강인한 체력',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '강직하다',
                mean: '성품이 강직하다',
                mean2: '성품이 강직하다',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '개운하다',
                mean: '몸이 개운하다 ',
                mean2: '몸이 개운하다 ',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '거뜬하다',
                mean: '거뜬한 일',
                mean2: '거뜬한 일',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '거룩하다',
                mean: '말씀이 거룩하다',
                mean2: '말씀이 거룩하다',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '거북하다',
                mean: '속이 거북하다 ',
                mean2: '속이 거북하다 ',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '거창하다',
                mean: '계획이 거창하다 ',
                mean2: '계획이 거창하다 ',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '건방지다',
                mean: '행동이 건방지다 ',
                mean2: '행동이 건방지다 ',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '건장하다',
                mean: '체격이 건장하다',
                mean2: '체격이 건장하다',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '걸맞다',
                mean: '나이에 걸맞다',
                mean2: '나이에 걸맞다',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '견고하다',
                mean: '제품이 견고하다',
                mean2: '제품이 견고하다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '경건하다',
                mean: '마음이 경건하다',
                mean2: '마음이 경건하다',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '경이롭다',
                mean: '경이로운 광경',
                mean2: '경이로운 광경',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '고귀하다',
                mean: '신분이 고귀하다',
                mean2: '신분이 고귀하다',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '고달프다',
                mean: '생활이 고달프다 ',
                mean2: '생활이 고달프다 ',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '고되다',
                mean: '일이 고되다',
                mean2: '일이 고되다',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '고약하다',
                mean: '냄새가 고약하다',
                mean2: '냄새가 고약하다',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '공공연하다',
                mean: '공공연한 비밀',
                mean2: '공공연한 비밀',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '공허하다',
                mean: '마음이 공허하다',
                mean2: '마음이 공허하다',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '과격하다',
                mean: '행동이 과격하다',
                mean2: '행동이 과격하다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '광범위하다',
                mean: '지역이 광범위하다',
                mean2: '지역이 광범위하다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '광활하다',
                mean: '평야가 광활하다',
                mean2: '평야가 광활하다',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '교묘하다',
                mean: '교묘한 속임수',
                mean2: '교묘한 속임수',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '교활하다',
                mean: '성격이 교활하다',
                mean2: '성격이 교활하다',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '구태의연하다',
                mean: '태도가 구태의연하다',
                mean2: '태도가 구태의연하다',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '궂다',
                mean: '날씨가 궂다',
                mean2: '날씨가 궂다',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '그윽하다',
                mean: '향기가 그윽하다',
                mean2: '향기가 그윽하다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '그지없다',
                mean: '기쁘기가 그지없다',
                mean2: '기쁘기가 그지없다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '급급하다',
                mean: '먹고살기에 급급하다',
                mean2: '먹고살기에 급급하다',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '기묘하다',
                mean: '기묘한 이야기',
                mean2: '기묘한 이야기',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '기이하다',
                mean: '생김새가 기이하다',
                mean2: '생김새가 기이하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '기특하다',
                mean: '행동이 기특하다',
                mean2: '행동이 기특하다',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '긴밀하다',
                mean: '긴밀한 관계',
                mean2: '긴밀한 관계',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '길쭉하다',
                mean: '얼굴이 길쭉하다',
                mean2: '얼굴이 길쭉하다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '까마득하다',
                mean: '앞길이 까마득하다',
                mean2: '앞길이 까마득하다',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '꺼림칙하다',
                mean: '왠지 꺼림칙하다',
                mean2: '왠지 꺼림칙하다',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '끈끈하다',
                mean: '끈끈한 가래침',
                mean2: '끈끈한 가래침',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '끈질기다',
                mean: '끈질긴 노력',
                mean2: '끈질긴 노력',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '나른하다',
                mean: '온몸이 나른하다',
                mean2: '온몸이 나른하다',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '나약하다',
                mean: '의지가 나약하다',
                mean2: '의지가 나약하다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '나지막하다',
                mean: '산이 나지막하다',
                mean2: '산이 나지막하다',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '난감하다',
                mean: '음식이 먹음직스럽다',
                mean2: '음식이 먹음직스럽다',
                audio: '',
            },
        ],
        adverb:[
            {
                seq: 1,
                isLearning: false,
                isFavorite: false,
                word: '가까스로',
                mean: '가까스로 살아남다 ',
                mean2: '가까스로 살아남다 ',
                audio: '',
            },
            {
                seq: 2,
                isLearning: false,
                isFavorite: false,
                word: '가뜩이나',
                mean: '가뜩이나 힘든데 ',
                mean2: '가뜩이나 힘든데 ',
                audio: '',
            },
            {
                seq: 3,
                isLearning: false,
                isFavorite: false,
                word: '가령',
                mean: '가령 비가 온다면',
                mean2: '가령 비가 온다면',
                audio: '',
            },
            {
                seq: 4,
                isLearning: false,
                isFavorite: false,
                word: '가히',
                mean: '가히 놀랄 만하다',
                mean2: '가히 놀랄 만하다',
                audio: '',
            },
            {
                seq: 5,
                isLearning: false,
                isFavorite: false,
                word: '각별히',
                mean: '각별히 생각하다',
                mean2: '각별히 생각하다',
                audio: '',
            },
            {
                seq: 6,
                isLearning: false,
                isFavorite: false,
                word: '감쪽같이',
                mean: '감쪽같이 사라지다 ',
                mean2: '감쪽같이 사라지다 ',
                audio: '',
            },
            {
                seq: 7,
                isLearning: false,
                isFavorite: false,
                word: '갓',
                mean: '갓',
                mean2: '갓',
                audio: '',
            },
            {
                seq: 8,
                isLearning: false,
                isFavorite: false,
                word: '거듭',
                mean: '거듭 강조하다',
                mean2: '거듭 강조하다',
                audio: '',
            },
            {
                seq: 9,
                isLearning: false,
                isFavorite: false,
                word: '거침없이',
                mean: '거침없이 말하다 ',
                mean2: '거침없이 말하다 ',
                audio: '',
            },
            {
                seq: 10,
                isLearning: false,
                isFavorite: false,
                word: '걸핏하면',
                mean: '걸핏하면 화내다 ',
                mean2: '걸핏하면 화내다 ',
                audio: '',
            },
            {
                seq: 11,
                isLearning: false,
                isFavorite: false,
                word: '고루',
                mean: '고루 나누다',
                mean2: '고루 나누다',
                audio: '',
            },
            {
                seq: 12,
                isLearning: false,
                isFavorite: false,
                word: '고스란히',
                mean: '고스란히 전하다 ',
                mean2: '고스란히 전하다 ',
                audio: '',
            },
            {
                seq: 13,
                isLearning: false,
                isFavorite: false,
                word: '고요히',
                mean: '고요히 잠들다',
                mean2: '고요히 잠들다',
                audio: '',
            },
            {
                seq: 14,
                isLearning: false,
                isFavorite: false,
                word: '곰곰이',
                mean: '곰곰이 생각하다 ',
                mean2: '곰곰이 생각하다 ',
                audio: '',
            },
            {
                seq: 15,
                isLearning: false,
                isFavorite: false,
                word: '공연히',
                mean: '공연히 화를 내다 ',
                mean2: '공연히 화를 내다 ',
                audio: '',
            },
            {
                seq: 16,
                isLearning: false,
                isFavorite: false,
                word: '과감히',
                mean: '과감히 맞서다',
                mean2: '과감히 맞서다',
                audio: '',
            },
            {
                seq: 17,
                isLearning: false,
                isFavorite: false,
                word: '구태여',
                mean: '구태여 말리지 않다',
                mean2: '구태여 말리지 않다',
                audio: '',
            },
            {
                seq: 18,
                isLearning: false,
                isFavorite: false,
                word: '그나저나',
                mean: '그나저나 다행이다',
                mean2: '그나저나 다행이다',
                audio: '',
            },
            {
                seq: 19,
                isLearning: false,
                isFavorite: false,
                word: '급기야',
                mean: '급기야 쓰러지다',
                mean2: '급기야 쓰러지다',
                audio: '',
            },
            {
                seq: 20,
                isLearning: false,
                isFavorite: false,
                word: '기꺼이',
                mean: '기꺼이 희생하다',
                mean2: '기꺼이 희생하다',
                audio: '',
            },
            {
                seq: 21,
                isLearning: false,
                isFavorite: false,
                word: '기껏',
                mean: '기껏 도와 줬더니',
                mean2: '기껏 도와 줬더니',
                audio: '',
            },
            {
                seq: 22,
                isLearning: false,
                isFavorite: false,
                word: '기어이',
                mean: '기어이 해 내다 ',
                mean2: '기어이 해 내다 ',
                audio: '',
            },
            {
                seq: 23,
                isLearning: false,
                isFavorite: false,
                word: '기어코',
                mean: '기어코 해 내다 ',
                mean2: '기어코 해 내다 ',
                audio: '',
            },
            {
                seq: 24,
                isLearning: false,
                isFavorite: false,
                word: '기필코',
                mean: '기필코 성공하다',
                mean2: '기필코 성공하다',
                audio: '',
            },
            {
                seq: 25,
                isLearning: false,
                isFavorite: false,
                word: '깊숙이',
                mean: '깊숙이 들어가다',
                mean2: '깊숙이 들어가다',
                audio: '',
            },
            {
                seq: 26,
                isLearning: false,
                isFavorite: false,
                word: '꼬치꼬치',
                mean: '꼬치꼬치 캐묻다',
                mean2: '꼬치꼬치 캐묻다',
                audio: '',
            },
            {
                seq: 27,
                isLearning: false,
                isFavorite: false,
                word: '꾹',
                mean: '꾹 누르다 ',
                mean2: '꾹 누르다 ',
                audio: '',
            },
            {
                seq: 28,
                isLearning: false,
                isFavorite: false,
                word: '끔찍이',
                mean: '끔찍이 싫어하다',
                mean2: '끔찍이 싫어하다',
                audio: '',
            },
            {
                seq: 29,
                isLearning: false,
                isFavorite: false,
                word: '난데없이',
                mean: '난데없이 나타나다',
                mean2: '난데없이 나타나다',
                audio: '',
            },
            {
                seq: 30,
                isLearning: false,
                isFavorite: false,
                word: '난생',
                mean: '난생 한 번도',
                mean2: '난생 한 번도',
                audio: '',
            },
            {
                seq: 31,
                isLearning: false,
                isFavorite: false,
                word: '남김없이',
                mean: '남김없이 먹다 ',
                mean2: '남김없이 먹다 ',
                audio: '',
            },
            {
                seq: 32,
                isLearning: false,
                isFavorite: false,
                word: '낱낱이',
                mean: '낱낱이 조사하다',
                mean2: '낱낱이 조사하다',
                audio: '',
            },
            {
                seq: 33,
                isLearning: false,
                isFavorite: false,
                word: '내지',
                mean: '내지',
                mean2: '내지',
                audio: '',
            },
            {
                seq: 34,
                isLearning: false,
                isFavorite: false,
                word: '느닷없이',
                mean: '느닷없이 나타나다',
                mean2: '느닷없이 나타나다',
                audio: '',
            },
            {
                seq: 35,
                isLearning: false,
                isFavorite: false,
                word: '다분히',
                mean: '다분히 고의적이다',
                mean2: '다분히 고의적이다',
                audio: '',
            },
            {
                seq: 36,
                isLearning: false,
                isFavorite: false,
                word: '다시금',
                mean: '다시금 시작하다',
                mean2: '다시금 시작하다',
                audio: '',
            },
            {
                seq: 37,
                isLearning: false,
                isFavorite: false,
                word: '다짜고짜',
                mean: '다짜고짜 따지다 ',
                mean2: '다짜고짜 따지다 ',
                audio: '',
            },
            {
                seq: 38,
                isLearning: false,
                isFavorite: false,
                word: '단단히',
                mean: '단단히 다지다 ',
                mean2: '단단히 다지다 ',
                audio: '',
            },
            {
                seq: 39,
                isLearning: false,
                isFavorite: false,
                word: '단번에',
                mean: '단번에 이해하다',
                mean2: '단번에 이해하다',
                audio: '',
            },
            {
                seq: 40,
                isLearning: false,
                isFavorite: false,
                word: '단숨에',
                mean: '단숨에 마시다',
                mean2: '단숨에 마시다',
                audio: '',
            },
            {
                seq: 41,
                isLearning: false,
                isFavorite: false,
                word: '단연',
                mean: '단연 으뜸이다',
                mean2: '단연 으뜸이다',
                audio: '',
            },
            {
                seq: 42,
                isLearning: false,
                isFavorite: false,
                word: '당당히',
                mean: '당당히 맞서다',
                mean2: '당당히 맞서다',
                audio: '',
            },
            {
                seq: 43,
                isLearning: false,
                isFavorite: false,
                word: '대뜸',
                mean: '대뜸 말하다',
                mean2: '대뜸 말하다',
                audio: '',
            },
            {
                seq: 44,
                isLearning: false,
                isFavorite: false,
                word: '더군다나',
                mean: '0',
                mean2: '0',
                audio: '',
            },
            {
                seq: 45,
                isLearning: false,
                isFavorite: false,
                word: '더더욱',
                mean: '0',
                mean2: '0',
                audio: '',
            },
            {
                seq: 46,
                isLearning: false,
                isFavorite: false,
                word: '더러00',
                mean: '더러 보이다',
                mean2: '더러 보이다',
                audio: '',
            },
            {
                seq: 47,
                isLearning: false,
                isFavorite: false,
                word: '덜컥',
                mean: '덜컥',
                mean2: '덜컥',
                audio: '',
            },
            {
                seq: 48,
                isLearning: false,
                isFavorite: false,
                word: '두루',
                mean: '두루 갖추다',
                mean2: '두루 갖추다',
                audio: '',
            },
            {
                seq: 49,
                isLearning: false,
                isFavorite: false,
                word: '둥둥',
                mean: '둥둥',
                mean2: '둥둥',
                audio: '',
            },
            {
                seq: 50,
                isLearning: false,
                isFavorite: false,
                word: '딱히',
                mean: '성실히 일하다',
                mean2: '성실히 일하다',
                audio: '',
            },
        ],
    }
];